// Copyright (c) Pixeval.
// Licensed under the GPL-3.0 License.

using System.Text.Json;
using System.Text.Json.Serialization;
using Mako.Global.Enum;
using Pixeval.Mcp.Dtos;

namespace Pixeval.Mcp;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, WriteIndented = true)]
[JsonSerializable(typeof(PixevalStatusDto))]
[JsonSerializable(typeof(PixevalCapabilitiesDto))]
[JsonSerializable(typeof(PixevalHelpDto))]
[JsonSerializable(typeof(PixevalHelpDocumentDto))]
[JsonSerializable(typeof(PixevalDownloadMacroSettingsDto))]
[JsonSerializable(typeof(PixevalDownloadMacroAnalysisDto))]
[JsonSerializable(typeof(PixevalDownloadMacroDiagnosticDto))]
[JsonSerializable(typeof(PixevalDownloadMacroHighlightDto))]
[JsonSerializable(typeof(PixevalDownloadMacroDefinitionDto))]
[JsonSerializable(typeof(PixevalSetDownloadMacroResultDto))]
[JsonSerializable(typeof(PixevalCursorPageDto))]
[JsonSerializable(typeof(PixevalWorkListDto))]
[JsonSerializable(typeof(PixevalUserListDto))]
[JsonSerializable(typeof(PixevalSeriesListDto))]
[JsonSerializable(typeof(PixevalSpotlightListDto))]
[JsonSerializable(typeof(PixevalTrendingTagListDto))]
[JsonSerializable(typeof(PixevalCommentListDto))]
[JsonSerializable(typeof(PixevalBookmarkTagListDto))]
[JsonSerializable(typeof(PixevalBookmarkTagDto))]
[JsonSerializable(typeof(PixevalWorkDto))]
[JsonSerializable(typeof(PixevalUserDto))]
[JsonSerializable(typeof(PixevalUserProfileDto))]
[JsonSerializable(typeof(PixevalSeriesDto))]
[JsonSerializable(typeof(PixevalSpotlightDto))]
[JsonSerializable(typeof(PixevalTagDto))]
[JsonSerializable(typeof(PixevalTrendingTagDto))]
[JsonSerializable(typeof(PixevalCommentDto))]
[JsonSerializable(typeof(PixevalStampDto))]
[JsonSerializable(typeof(PixevalOperationResultDto))]
[JsonSerializable(typeof(PixevalBookmarkResultDto))]
[JsonSerializable(typeof(PixevalFollowUserResultDto))]
[JsonSerializable(typeof(PixevalWatchLaterResultDto))]
[JsonSerializable(typeof(PixevalThumbnailInfoDto))]
[JsonSerializable(typeof(PixevalThumbnailImageDto))]
[JsonSerializable(typeof(PixevalSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalApplicationSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalNetworkSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalPixivNameResolverSummaryDto))]
[JsonSerializable(typeof(PixevalGitHubNameResolverSummaryDto))]
[JsonSerializable(typeof(PixevalBrowsingExperienceSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalSearchSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalDownloadSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalMcpSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalNovelSettingsSummaryDto))]
[JsonSerializable(typeof(PixevalMcpDownloadTaskDto))]
[JsonSerializable(typeof(PixevalMcpDownloadTaskListDto))]
[JsonSerializable(typeof(PixevalDownloadTaskControlResultDto))]
[JsonSerializable(typeof(PixevalWorkFilterAnalysisDto))]
[JsonSerializable(typeof(PixevalWorkFilterQueryDto))]
[JsonSerializable(typeof(PixevalWorkFilterDiagnosticDto))]
[JsonSerializable(typeof(PixevalWorkFilterCompletionDto))]
[JsonSerializable(typeof(PixevalHistoryListDto))]
[JsonSerializable(typeof(PixevalHistoryItemDto))]
[JsonSerializable(typeof(PixevalSearchHistoryDto))]
[JsonSerializable(typeof(PixevalHistoryArtworkDto))]
[JsonSerializable(typeof(PixevalDownloadHistoryDto))]
[JsonSerializable(typeof(PixevalWorkSubscriptionDto))]
[JsonSerializable(typeof(PixevalWorkSubscriptionOperationResultDto))]
[JsonSerializable(typeof(PixevalExtensionListDto))]
[JsonSerializable(typeof(PixevalExtensionTypeStatisticDto))]
[JsonSerializable(typeof(PixevalExtensionHostDto))]
[JsonSerializable(typeof(PixevalExtensionSettingsEntryDto))]
[JsonSerializable(typeof(PixevalExtensionEnumItemDto))]
[JsonSerializable(typeof(PixevalNovelContentDto))]
[JsonSerializable(typeof(PixevalNovelRatingDto))]
[JsonSerializable(typeof(PixevalNovelMarkerDto))]
[JsonSerializable(typeof(PixevalNovelNavigationPairDto))]
[JsonSerializable(typeof(PixevalNovelNavigationDto))]
[JsonSerializable(typeof(PixevalNovelImageDto))]
[JsonSerializable(typeof(PixevalNovelIllustrationDto))]
[JsonSerializable(typeof(PixevalNovelUserDto))]
[JsonSerializable(typeof(PixevalNovelGlossaryItemDto))]
[JsonSerializable(typeof(PixevalSauceNaoSearchDto))]
[JsonSerializable(typeof(PixevalSauceNaoResultDto))]
[JsonSerializable(typeof(PixevalHelpTopic))]
[JsonSerializable(typeof(PixevalHelpTopic?))]
[JsonSerializable(typeof(WorkType))]
[JsonSerializable(typeof(WorkType?))]
[JsonSerializable(typeof(SimpleWorkType))]
[JsonSerializable(typeof(SimpleWorkType?))]
[JsonSerializable(typeof(PrivacyPolicy))]
[JsonSerializable(typeof(RankOption))]
[JsonSerializable(typeof(WorkSortOption))]
[JsonSerializable(typeof(SearchIllustrationTagMatchOption))]
[JsonSerializable(typeof(SearchIllustrationContentType))]
[JsonSerializable(typeof(SearchIllustrationRatioPattern))]
[JsonSerializable(typeof(SearchNovelTagMatchOption))]
[JsonSerializable(typeof(SearchNovelContentLengthOption))]
[JsonSerializable(typeof(PixevalHistoryType))]
[JsonSerializable(typeof(PixevalDownloadAction))]
[JsonSerializable(typeof(PixevalWorkSubscriptionType))]
[JsonSerializable(typeof(PixevalWorkSubscriptionType?))]
[JsonSerializable(typeof(PixevalWorkSubscriptionWorkKind))]
[JsonSerializable(typeof(PixevalWorkSubscriptionWorkKind?))]
[JsonSerializable(typeof(IReadOnlyList<long>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyList<PixevalHelpTopic>))]
internal sealed partial class PixevalMcpJsonContext : JsonSerializerContext;
