//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixeval.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixeval.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Pixeval 的本地化字符串。
        /// </summary>
        public static string AboutPixeval {
            get {
                return ResourceManager.GetString("AboutPixeval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to favorite 的本地化字符串。
        /// </summary>
        public static string AddSpotlightToFavorite {
            get {
                return ResourceManager.GetString("AddSpotlightToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication timeout, please check your network environment 的本地化字符串。
        /// </summary>
        public static string AppApiAuthenticateTimeout {
            get {
                return ResourceManager.GetString("AppApiAuthenticateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to download all the illustrations, this may lead the program into a temporarily unresponsive 的本地化字符串。
        /// </summary>
        public static string BatchDownloadAcknowledgment {
            get {
                return ResourceManager.GetString("BatchDownloadAcknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browsing History Counts 的本地化字符串。
        /// </summary>
        public static string BrowsingHistoryCount {
            get {
                return ResourceManager.GetString("BrowsingHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find any result :( 的本地化字符串。
        /// </summary>
        public static string CannotFindResult {
            get {
                return ResourceManager.GetString("CannotFindResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find specified certificate 的本地化字符串。
        /// </summary>
        public static string CannotFindSpecifiedCertificate {
            get {
                return ResourceManager.GetString("CannotFindSpecifiedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, Pixeval cannot find the user you searching for, please check you input and try again~ 的本地化字符串。
        /// </summary>
        public static string CannotFindUser {
            get {
                return ResourceManager.GetString("CannotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find the corresponds Content-Length parameter 的本地化字符串。
        /// </summary>
        public static string CannotRetrieveContentLengthHeader {
            get {
                return ResourceManager.GetString("CannotRetrieveContentLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We detected that required certificate is not installed yet on this machine which will causing the login procedure becomes invalid, we will try to install the certificate in the next few steps, there might be a popup window during the installation, please click OK, the private key of this certificate is guaranteed not to be distributed 的本地化字符串。
        /// </summary>
        public static string CertificateInstallationIsRequired {
            get {
                return ResourceManager.GetString("CertificateInstallationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install CA Root Certificate 的本地化字符串。
        /// </summary>
        public static string CertificateInstallationIsRequiredTitle {
            get {
                return ResourceManager.GetString("CertificateInstallationIsRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter advanced search expression 的本地化字符串。
        /// </summary>
        public static string ConditionBoxHint {
            get {
                return ResourceManager.GetString("ConditionBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format: &lt;capture&gt;
        ///        Allowed queries: &lt;ID&gt;/&lt;Tag&gt;/&lt;Title&gt;/&lt;!tag-to-be-excluded&gt;/&lt;&lt;desire-width&gt;x&lt;desire-height&gt;&gt; 的本地化字符串。
        /// </summary>
        public static string ConditionBoxTooltip {
            get {
                return ResourceManager.GetString("ConditionBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy download path 的本地化字符串。
        /// </summary>
        public static string CopyDownloadPath {
            get {
                return ResourceManager.GetString("CopyDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixeval requires Visual C++ Redistributable 2015/2017/2019 x64 support, otherwise some function will be limited. Please download the newest VC++ Redistributable at https://support.microsoft.com/zh-cn/help/2977003/the-latest-supported-visual-c-downloads, the link has been copied to clipboard 的本地化字符串。
        /// </summary>
        public static string CppRedistributableRequired {
            get {
                return ResourceManager.GetString("CppRedistributableRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No VC++ Redistributable 2015/2017/2019 detected 的本地化字符串。
        /// </summary>
        public static string CppRedistributableRequiredTitle {
            get {
                return ResourceManager.GetString("CppRedistributableRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create folder when download from user 的本地化字符串。
        /// </summary>
        public static string CreateNewFolderWhenDownloadFromUser {
            get {
                return ResourceManager.GetString("CreateNewFolderWhenDownloadFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download All 的本地化字符串。
        /// </summary>
        public static string DownloadAllInCurrentList {
            get {
                return ResourceManager.GetString("DownloadAllInCurrentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illust download location 的本地化字符串。
        /// </summary>
        public static string DownloadLocation {
            get {
                return ResourceManager.GetString("DownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///You can use the following macros as placeholders of their actual values that will be represented at runtime
        ///1. General purpose macros, These macros will work regardless of the kind of current illustration
        ///                1. {illust.ext} Referring to the extension name of the current picture(e.g. jpg png gif), the periods before the extension name needs to be added manually, if this macro
        ///                   is not present at the end of the given path, it will be automatically appended to the end, with a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string DownloadPathSyntaxToolTip {
            get {
                return ResourceManager.GetString("DownloadPathSyntaxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download&amp;Browse 的本地化字符串。
        /// </summary>
        public static string DownloadQueueAndHistory {
            get {
                return ResourceManager.GetString("DownloadQueueAndHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browsing History 的本地化字符串。
        /// </summary>
        public static string DownloadQueueBrowsingHistory {
            get {
                return ResourceManager.GetString("DownloadQueueBrowsingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded 的本地化字符串。
        /// </summary>
        public static string DownloadQueueDownloaded {
            get {
                return ResourceManager.GetString("DownloadQueueDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string DownloadQueueDownloading {
            get {
                return ResourceManager.GetString("DownloadQueueDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is empty here, Let&apos;s go get some! 的本地化字符串。
        /// </summary>
        public static string DownloadQueueEmptyNotifier {
            get {
                return ResourceManager.GetString("DownloadQueueEmptyNotifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is empty here, Let&apos;s go get some! 的本地化字符串。
        /// </summary>
        public static string DownloadQueueHistoryListIsEmpty {
            get {
                return ResourceManager.GetString("DownloadQueueHistoryListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the list 的本地化字符串。
        /// </summary>
        public static string DownloadQueueRemoveAllFromList {
            get {
                return ResourceManager.GetString("DownloadQueueRemoveAllFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from list 的本地化字符串。
        /// </summary>
        public static string DownloadQueueRemoveFromDownloading {
            get {
                return ResourceManager.GetString("DownloadQueueRemoveFromDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from list 的本地化字符串。
        /// </summary>
        public static string DownloadQueueRemoveFromList {
            get {
                return ResourceManager.GetString("DownloadQueueRemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View illust 的本地化字符串。
        /// </summary>
        public static string DownloadQueueShowDownloadIllust {
            get {
                return ResourceManager.GetString("DownloadQueueShowDownloadIllust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string DownloadSingleIllustration {
            get {
                return ResourceManager.GetString("DownloadSingleIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Spotlight 的本地化字符串。
        /// </summary>
        public static string DownloadSpotlight {
            get {
                return ResourceManager.GetString("DownloadSpotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download To... 的本地化字符串。
        /// </summary>
        public static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] dqueue {
            get {
                object obj = ResourceManager.GetObject("dqueue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Account or Password error 的本地化字符串。
        /// </summary>
        public static string EmailOrPasswordIsWrong {
            get {
                return ResourceManager.GetString("EmailOrPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account or Password cannot be null 的本地化字符串。
        /// </summary>
        public static string EmptyEmailOrPasswordIsNotAllowed {
            get {
                return ResourceManager.GetString("EmptyEmailOrPasswordIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorite Spotlights 的本地化字符串。
        /// </summary>
        public static string FavoriteSpotlights {
            get {
                return ResourceManager.GetString("FavoriteSpotlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feeds 的本地化字符串。
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caching Policy: File (Prefer reduce memory usage) 的本地化字符串。
        /// </summary>
        public static string FileCachePolicy {
            get {
                return ResourceManager.GetString("FileCachePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill with your Cookie 的本地化字符串。
        /// </summary>
        public static string FillWithWebCookie {
            get {
                return ResourceManager.GetString("FillWithWebCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a GIF 的本地化字符串。
        /// </summary>
        public static string GifIllustrationHint {
            get {
                return ResourceManager.GetString("GifIllustrationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] iconfont {
            get {
                object obj = ResourceManager.GetObject("iconfont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] iconfontex {
            get {
                object obj = ResourceManager.GetObject("iconfontex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Specified ID is not exist, please check you input and try again~ 的本地化字符串。
        /// </summary>
        public static string IdDoNotExists {
            get {
                return ResourceManager.GetString("IdDoNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must enter pure number when searching illust ID~ 的本地化字符串。
        /// </summary>
        public static string IdIllegal {
            get {
                return ResourceManager.GetString("IdIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add bookmark 的本地化字符串。
        /// </summary>
        public static string IllustBrowserBookmark {
            get {
                return ResourceManager.GetString("IllustBrowserBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string IllustBrowserDownload {
            get {
                return ResourceManager.GetString("IllustBrowserDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illust ID:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserIllustId {
            get {
                return ResourceManager.GetString("IllustBrowserIllustId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #Illust Tags:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserIllustTag {
            get {
                return ResourceManager.GetString("IllustBrowserIllustTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bookmark silently 的本地化字符串。
        /// </summary>
        public static string IllustBrowserPrivateBookmark {
            get {
                return ResourceManager.GetString("IllustBrowserPrivateBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove bookmark 的本地化字符串。
        /// </summary>
        public static string IllustBrowserRemoveBookmark {
            get {
                return ResourceManager.GetString("IllustBrowserRemoveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserResolution {
            get {
                return ResourceManager.GetString("IllustBrowserResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as wallpaper 的本地化字符串。
        /// </summary>
        public static string IllustBrowserSetWallpaper {
            get {
                return ResourceManager.GetString("IllustBrowserSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share 的本地化字符串。
        /// </summary>
        public static string IllustBrowserShareLink {
            get {
                return ResourceManager.GetString("IllustBrowserShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Bookmarks:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserTotalBookmarks {
            get {
                return ResourceManager.GetString("IllustBrowserTotalBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total View:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserTotalViews {
            get {
                return ResourceManager.GetString("IllustBrowserTotalViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Date:  的本地化字符串。
        /// </summary>
        public static string IllustBrowserUploadDate {
            get {
                return ResourceManager.GetString("IllustBrowserUploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View in browser 的本地化字符串。
        /// </summary>
        public static string IllustBrowserViewInBrowser {
            get {
                return ResourceManager.GetString("IllustBrowserViewInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranking 的本地化字符串。
        /// </summary>
        public static string IllustRanking {
            get {
                return ResourceManager.GetString("IllustRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image mirror server url 的本地化字符串。
        /// </summary>
        public static string ImageMirrorServerUrl {
            get {
                return ResourceManager.GetString("ImageMirrorServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you want to use another image server instead of default one(i.pximg.net), fill it here, please do nothing if you don&apos;t know what does it means 的本地化字符串。
        /// </summary>
        public static string ImageMirrorServerUrlHint {
            get {
                return ResourceManager.GetString("ImageMirrorServerUrlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click search button after enter keyword~ 的本地化字符串。
        /// </summary>
        public static string InputIsEmpty {
            get {
                return ResourceManager.GetString("InputIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given path is not a valid directory path 的本地化字符串。
        /// </summary>
        public static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] logo_only {
            get {
                object obj = ResourceManager.GetObject("logo_only", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a collection with {0} image inside 的本地化字符串。
        /// </summary>
        public static string MangaIllustrationHintFormat {
            get {
                return ResourceManager.GetString("MangaIllustrationHintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caching Policy: Memory (Prefer load speed) 的本地化字符串。
        /// </summary>
        public static string MemoryCachePolicy {
            get {
                return ResourceManager.GetString("MemoryCachePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum bookmark 的本地化字符串。
        /// </summary>
        public static string MinBookmarkRequired {
            get {
                return ResourceManager.GetString("MinBookmarkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the minimum bookmark requirement when performing a search operation, only valid when the operation is UserUpdate/Gallery/Upload/Ranking/Search/Recommend, all illusts of which has a lesser bookmarks will be filtered out 的本地化字符串。
        /// </summary>
        public static string MinimumBookmarkToolTip {
            get {
                return ResourceManager.GetString("MinimumBookmarkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s already a Pixeval instance running 的本地化字符串。
        /// </summary>
        public static string MultiplePixevalInstanceDetected {
            get {
                return ResourceManager.GetString("MultiplePixevalInstanceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot running two Pixeval at the same time! 的本地化字符串。
        /// </summary>
        public static string MultiplePixevalInstanceDetectedTitle {
            get {
                return ResourceManager.GetString("MultiplePixevalInstanceDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Following 的本地化字符串。
        /// </summary>
        public static string MyFollowing {
            get {
                return ResourceManager.GetString("MyFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Collection 的本地化字符串。
        /// </summary>
        public static string MyGallery {
            get {
                return ResourceManager.GetString("MyGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find the path specified, please check if the file has been deleted 的本地化字符串。
        /// </summary>
        public static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] pixeval_ca {
            get {
                object obj = ResourceManager.GetObject("pixeval_ca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] pixeval_server_cert {
            get {
                object obj = ResourceManager.GetObject("pixeval_server_cert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Pixeval Settings 的本地化字符串。
        /// </summary>
        public static string PixevalSettings {
            get {
                return ResourceManager.GetString("PixevalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An update for Pixeval is available, update now? 的本地化字符串。
        /// </summary>
        public static string PixevalUpdateAvailable {
            get {
                return ResourceManager.GetString("PixevalUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Release Updated 的本地化字符串。
        /// </summary>
        public static string PixevalUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("PixevalUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: {0} 的本地化字符串。
        /// </summary>
        public static string PixevalVersionFormat {
            get {
                return ResourceManager.GetString("PixevalVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        public static string PleaseSelectFile {
            get {
                return ResourceManager.GetString("PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Location 的本地化字符串。
        /// </summary>
        public static string PleaseSelectLocation {
            get {
                return ResourceManager.GetString("PleaseSelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private 的本地化字符串。
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public 的本地化字符串。
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon pxlogo {
            get {
                object obj = ResourceManager.GetObject("pxlogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, Pixeval cannot find any illust according to current settings, maybe the page number you specified is too big/keyword does not exist/did not collect any illust, please check and try again~ 的本地化字符串。
        /// </summary>
        public static string QueryNotResponding {
            get {
                return ResourceManager.GetString("QueryNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Single Illust 的本地化字符串。
        /// </summary>
        public static string QuerySingleIllust {
            get {
                return ResourceManager.GetString("QuerySingleIllust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Single User 的本地化字符串。
        /// </summary>
        public static string QuerySingleUser {
            get {
                return ResourceManager.GetString("QuerySingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search User 的本地化字符串。
        /// </summary>
        public static string QueryUser {
            get {
                return ResourceManager.GetString("QueryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added all to downloaded queue 的本地化字符串。
        /// </summary>
        public static string QueuedAllToDownload {
            get {
                return ResourceManager.GetString("QueuedAllToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added to download queue 的本地化字符串。
        /// </summary>
        public static string QueuedDownload {
            get {
                return ResourceManager.GetString("QueuedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranking date cannot be empty 的本地化字符串。
        /// </summary>
        public static string RankDateCannotBeNull {
            get {
                return ResourceManager.GetString("RankDateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixeval cannot show this illustrations according to your preference 的本地化字符串。
        /// </summary>
        public static string RankNeedR18On {
            get {
                return ResourceManager.GetString("RankNeedR18On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        public static string RankOptionDay {
            get {
                return ResourceManager.GetString("RankOptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FemaleDaily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayFemale {
            get {
                return ResourceManager.GetString("RankOptionDayFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FemaleR-18Daily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayFemaleR18 {
            get {
                return ResourceManager.GetString("RankOptionDayFemaleR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaleDaily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayMale {
            get {
                return ResourceManager.GetString("RankOptionDayMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaleR-18Daily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayMaleR18 {
            get {
                return ResourceManager.GetString("RankOptionDayMaleR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MangaDaily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayManga {
            get {
                return ResourceManager.GetString("RankOptionDayManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R-18Daily 的本地化字符串。
        /// </summary>
        public static string RankOptionDayR18 {
            get {
                return ResourceManager.GetString("RankOptionDayR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        public static string RankOptionMonth {
            get {
                return ResourceManager.GetString("RankOptionMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        public static string RankOptionWeek {
            get {
                return ResourceManager.GetString("RankOptionWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MangaWeekly 的本地化字符串。
        /// </summary>
        public static string RankOptionWeekManga {
            get {
                return ResourceManager.GetString("RankOptionWeekManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin 的本地化字符串。
        /// </summary>
        public static string RankOptionWeekOriginal {
            get {
                return ResourceManager.GetString("RankOptionWeekOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R-18Weekly 的本地化字符串。
        /// </summary>
        public static string RankOptionWeekR18 {
            get {
                return ResourceManager.GetString("RankOptionWeekR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R-18GWeekly 的本地化字符串。
        /// </summary>
        public static string RankOptionWeekR18G {
            get {
                return ResourceManager.GetString("RankOptionWeekR18G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rookie 的本地化字符串。
        /// </summary>
        public static string RankOptionWeekRookie {
            get {
                return ResourceManager.GetString("RankOptionWeekRookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommend 的本地化字符串。
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show recommended illustrators at homepage 的本地化字符串。
        /// </summary>
        public static string RecommendIllustrationToolTip {
            get {
                return ResourceManager.GetString("RecommendIllustrationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn Around 的本地化字符串。
        /// </summary>
        public static string RecommendIllustratorTurnPage {
            get {
                return ResourceManager.GetString("RecommendIllustratorTurnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This section requires Cookie from WebAPI, please follow https://sora.ink/pixiv-cookie to copy your cookie and paste it to the correspond text box in the Settings dialog 的本地化字符串。
        /// </summary>
        public static string RequiresWebCookie {
            get {
                return ResourceManager.GetString("RequiresWebCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restrict Policy 的本地化字符串。
        /// </summary>
        public static string RestrictPolicy {
            get {
                return ResourceManager.GetString("RestrictPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fold Sidebar 的本地化字符串。
        /// </summary>
        public static string RetractSidebar {
            get {
                return ResourceManager.GetString("RetractSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap saucenao {
            get {
                object obj = ResourceManager.GetObject("saucenao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 You can only upload one file 的本地化字符串。
        /// </summary>
        public static string SauceNaoFileCountLimit {
            get {
                return ResourceManager.GetString("SauceNaoFileCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Location 的本地化字符串。
        /// </summary>
        public static string SauceNaoFileLocationHint {
            get {
                return ResourceManager.GetString("SauceNaoFileLocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload And Search 的本地化字符串。
        /// </summary>
        public static string SauceNaoUploadAndSearch {
            get {
                return ResourceManager.GetString("SauceNaoUploadAndSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the keyword~(￣▽￣)~* 的本地化字符串。
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SauceNAO 的本地化字符串。
        /// </summary>
        public static string SearchImageBySource {
            get {
                return ResourceManager.GetString("SearchImageBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring following list... 的本地化字符串。
        /// </summary>
        public static string SearchingFollower {
            get {
                return ResourceManager.GetString("SearchingFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring collection... 的本地化字符串。
        /// </summary>
        public static string SearchingGallery {
            get {
                return ResourceManager.GetString("SearchingGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring daily recommend... 的本地化字符串。
        /// </summary>
        public static string SearchingRecommend {
            get {
                return ResourceManager.GetString("SearchingRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring spotlight... 的本地化字符串。
        /// </summary>
        public static string SearchingSpotlight {
            get {
                return ResourceManager.GetString("SearchingSpotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring feeds... 的本地化字符串。
        /// </summary>
        public static string SearchingTrends {
            get {
                return ResourceManager.GetString("SearchingTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquiring follow updates... 的本地化字符串。
        /// </summary>
        public static string SearchingUserUpdates {
            get {
                return ResourceManager.GetString("SearchingUserUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How many pages will be included when searching 的本地化字符串。
        /// </summary>
        public static string SearchPageCountHint {
            get {
                return ResourceManager.GetString("SearchPageCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates how many pages will be searched during an illust searching, each page contains 30 illusts, acceptable value range: [1,100] 的本地化字符串。
        /// </summary>
        public static string SearchPageCountToolTip {
            get {
                return ResourceManager.GetString("SearchPageCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search starts from 的本地化字符串。
        /// </summary>
        public static string SearchPageStart {
            get {
                return ResourceManager.GetString("SearchPageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates which page index will be used as start index when performing an illust searching, each page contains 30 illusts, acceptable value range: [1,+∞) 的本地化字符串。
        /// </summary>
        public static string SearchPageStartToolTip {
            get {
                return ResourceManager.GetString("SearchPageStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: Spotlight search 10 items once, illustration search 30 items once 的本地化字符串。
        /// </summary>
        public static string SearchPerPageCountHint {
            get {
                return ResourceManager.GetString("SearchPerPageCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string SelectCultureInfo {
            get {
                return ResourceManager.GetString("SelectCultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied to clipboard 的本地化字符串。
        /// </summary>
        public static string ShareLinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("ShareLinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email/Pixiv ID 的本地化字符串。
        /// </summary>
        public static string SignInAccount {
            get {
                return ResourceManager.GetString("SignInAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging in... 的本地化字符串。
        /// </summary>
        public static string SignInLoggingIn {
            get {
                return ResourceManager.GetString("SignInLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string SignInPassword {
            get {
                return ResourceManager.GetString("SignInPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating Session... 的本地化字符串。
        /// </summary>
        public static string SignInUpdatingSession {
            get {
                return ResourceManager.GetString("SignInUpdatingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by population 的本地化字符串。
        /// </summary>
        public static string SortByPopulation {
            get {
                return ResourceManager.GetString("SortByPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates Pixeval should sorted illusts by popularity(bookmarks) when performing a search operation, only valid when the operation is Recommend/UserUpdate/Ranking/Gallery/Search/Upload 的本地化字符串。
        /// </summary>
        public static string SortByPopulationToolTip {
            get {
                return ResourceManager.GetString("SortByPopulationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spotlight 的本地化字符串。
        /// </summary>
        public static string Spotlight {
            get {
                return ResourceManager.GetString("Spotlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spotlight search starts from 的本地化字符串。
        /// </summary>
        public static string SpotlightSearchPageStart {
            get {
                return ResourceManager.GetString("SpotlightSearchPageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates which page index will be used as start index when performing a spotlight traversal, each page contains 10 spotlights, acceptable value range: [1,+∞) 的本地化字符串。
        /// </summary>
        public static string SpotlightSearchPageStartToolTip {
            get {
                return ResourceManager.GetString("SpotlightSearchPageStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Me 的本地化字符串。
        /// </summary>
        public static string SupportMe {
            get {
                return ResourceManager.GetString("SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exact Match 的本地化字符串。
        /// </summary>
        public static string TagMatchingExactMatch {
            get {
                return ResourceManager.GetString("TagMatchingExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partial Match 的本地化字符串。
        /// </summary>
        public static string TagMatchingPartialMatch {
            get {
                return ResourceManager.GetString("TagMatchingPartialMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title And Caption 的本地化字符串。
        /// </summary>
        public static string TagMatchingTitleAndCaption {
            get {
                return ResourceManager.GetString("TagMatchingTitleAndCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag matching 的本地化字符串。
        /// </summary>
        public static string TagMatchOption {
            get {
                return ResourceManager.GetString("TagMatchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the tags to be exclude, separate them with space 的本地化字符串。
        /// </summary>
        public static string TagsToBeExclude {
            get {
                return ResourceManager.GetString("TagsToBeExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the tags to be include, separate them with space 的本地化字符串。
        /// </summary>
        public static string TagsToBeInclude {
            get {
                return ResourceManager.GetString("TagsToBeInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This login session requires finish recaptcha manually 的本地化字符串。
        /// </summary>
        public static string ThisLoginSessionRequiresRecaptcha {
            get {
                return ResourceManager.GetString("ThisLoginSessionRequiresRecaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on failed 的本地化字符串。
        /// </summary>
        public static string ToggleR18OnFailed {
            get {
                return ResourceManager.GetString("ToggleR18OnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully turn on WebApi R-18/R-18G 的本地化字符串。
        /// </summary>
        public static string ToggleR18OnSuccess {
            get {
                return ResourceManager.GetString("ToggleR18OnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collected 的本地化字符串。
        /// </summary>
        public static string TrendsAddBookmark {
            get {
                return ResourceManager.GetString("TrendsAddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Followed 的本地化字符串。
        /// </summary>
        public static string TrendsAddFavorite {
            get {
                return ResourceManager.GetString("TrendsAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posted 的本地化字符串。
        /// </summary>
        public static string TrendsAddIllust {
            get {
                return ResourceManager.GetString("TrendsAddIllust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to turn on WebApi R-18/R-18G 的本地化字符串。
        /// </summary>
        public static string TryingToToggleR18Switch {
            get {
                return ResourceManager.GetString("TryingToToggleR18Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off dialog animation 的本地化字符串。
        /// </summary>
        public static string TurnOffAnimation {
            get {
                return ResourceManager.GetString("TurnOffAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off the animation of DialogHost, which may improve the overall performance on some computers 的本地化字符串。
        /// </summary>
        public static string TurnOffAnimationToolTip {
            get {
                return ResourceManager.GetString("TurnOffAnimationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off R-18/R-18G 的本地化字符串。
        /// </summary>
        public static string TurnOffR18 {
            get {
                return ResourceManager.GetString("TurnOffR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Cache (Not recommended) 的本地化字符串。
        /// </summary>
        public static string TurnOnCache {
            get {
                return ResourceManager.GetString("TurnOnCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on SNI bypass(otherwise proxy is required if you&apos;re currently at China mainland) 的本地化字符串。
        /// </summary>
        public static string TurnOnDirectConnect {
            get {
                return ResourceManager.GetString("TurnOnDirectConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommend illustrator 的本地化字符串。
        /// </summary>
        public static string TurnOnIllustratorRecommend {
            get {
                return ResourceManager.GetString("TurnOnIllustratorRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on WebApi R18/R18G 的本地化字符串。
        /// </summary>
        public static string TurnOnWebR18 {
            get {
                return ResourceManager.GetString("TurnOnWebR18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified uri is incorrect 的本地化字符串。
        /// </summary>
        public static string UriFormIncorrect {
            get {
                return ResourceManager.GetString("UriFormIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow 的本地化字符串。
        /// </summary>
        public static string UserBrowserFollow {
            get {
                return ResourceManager.GetString("UserBrowserFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow 的本地化字符串。
        /// </summary>
        public static string UserBrowserFollowCountHint {
            get {
                return ResourceManager.GetString("UserBrowserFollowCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection 的本地化字符串。
        /// </summary>
        public static string UserBrowserGallerySelector {
            get {
                return ResourceManager.GetString("UserBrowserGallerySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illustration 的本地化字符串。
        /// </summary>
        public static string UserBrowserIllustSelector {
            get {
                return ResourceManager.GetString("UserBrowserIllustSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Silently 的本地化字符串。
        /// </summary>
        public static string UserBrowserPrivateFollow {
            get {
                return ResourceManager.GetString("UserBrowserPrivateFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Followed 的本地化字符串。
        /// </summary>
        public static string UserBrowserUnFollow {
            get {
                return ResourceManager.GetString("UserBrowserUnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User ID: {0} 的本地化字符串。
        /// </summary>
        public static string UserIdHintFormat {
            get {
                return ResourceManager.GetString("UserIdHintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must enter pure number when searching user ID~ 的本地化字符串。
        /// </summary>
        public static string UserIdIllegal {
            get {
                return ResourceManager.GetString("UserIdIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow 的本地化字符串。
        /// </summary>
        public static string UserPreviewPopupFollow {
            get {
                return ResourceManager.GetString("UserPreviewPopupFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnFollow 的本地化字符串。
        /// </summary>
        public static string UserPreviewPopupUnFollow {
            get {
                return ResourceManager.GetString("UserPreviewPopupUnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        public static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input value is not integer 的本地化字符串。
        /// </summary>
        public static string ValueIsNotInteger {
            get {
                return ResourceManager.GetString("ValueIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebApi login timeout, please check your network environment 的本地化字符串。
        /// </summary>
        public static string WebApiAuthenticateTimeout {
            get {
                return ResourceManager.GetString("WebApiAuthenticateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixeval requires WebView2 Runtime as a countermeasure of the new auth method of Pixiv, go to https://go.microsoft.com/fwlink/p/?LinkId=2124703 to download the runtime and install it, the link has been copied to your clipboard, restart Pixeval after your installation 的本地化字符串。
        /// </summary>
        public static string WebView2DownloadIsRequired {
            get {
                return ResourceManager.GetString("WebView2DownloadIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
