name: 功能建议
description: 提出你希望软件实现的新功能或优化
title: 功能的简要叙述
labels: [feature ✨]
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: 建议类型
      options:
        - 新功能
        - 功能优化
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Pixeval的版本
      options:
        - WinUI3
  - type: textarea
    validations:
      required: true
    attributes:
      label: 描述
      description: 请简练、完整地描述你的建议
  - type: textarea
    attributes:
      label: 图片
      description: 如果可以，请图文并茂地叙述你的建议
  - type: textarea
    attributes:
      label: 其他信息
      description: 任何你想说的其他信息
