//------------------------------------------------------------------------------  
// <auto-generated>  
//     Running by T4 Text Templates on .NET Framework 4.8.9325.0
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Pixeval
{
    public static class AboutPageResources
    {
        public const string DependenciesContentTextBlockText = "AboutPage.DependenciesContentTextBlock.Text";
        public const string DependenciesSubtitleTextBlockText = "AboutPage.DependenciesSubtitleTextBlock.Text";
        public const string OpenSourceLicenseContentPartIText = "AboutPage.OpenSourceLicenseContentPartI.Text";
        public const string OpenSourceLicenseContentPartIIText = "AboutPage.OpenSourceLicenseContentPartII.Text";
        public const string OpenSourceLicenseHyperlinkContentText = "AboutPage.OpenSourceLicenseHyperlinkContent.Text";
        public const string OpenSourceLicenseSubtitleTextBlockText = "AboutPage.OpenSourceLicenseSubtitleTextBlock.Text";
        public const string SpecialThanksContentTextBlockText = "AboutPage.SpecialThanksContentTextBlock.Text";
        public const string SpecialThanksSubtitleTextBlockText = "AboutPage.SpecialThanksSubtitleTextBlock.Text";
        public const string SupportMeContentPartIText = "AboutPage.SupportMeContentPartI.Text";
        public const string SupportMeContentPartIIText = "AboutPage.SupportMeContentPartII.Text";
        public const string SupportMeHyperlinkContentText = "AboutPage.SupportMeHyperlinkContent.Text";
        public const string SupportMeSubtitleTextBlockText = "AboutPage.SupportMeSubtitleTextBlock.Text";
        public const string TitleTextBlockText = "AboutPage.TitleTextBlock.Text";
    }
    public static class ActivationsResources
    {
        public const string ActivationFailedContentFormatted = "Activations.ActivationFailedContentFormatted";
        public const string ActivationFailedTitle = "Activations.ActivationFailedTitle";
    }
    public static class AdvancedItemsViewResources
    {
        public const string Grid = "AdvancedItemsView.Grid";
        public const string LinedFlow = "AdvancedItemsView.LinedFlow";
        public const string LoadingMore = "AdvancedItemsView.LoadingMore";
    }
    public static class AppSettingsResources
    {
        public const string AppDefaultFontFamilyName = "AppSettings.AppDefaultFontFamilyName";
        public const string Bcl47 = "AppSettings.Bcl47";
    }
    public static class BookmarksPageResources
    {
        public const string TagComboBoxPlaceholderText = "BookmarksPage.TagComboBox.PlaceholderText";
    }
    public static class CommentRepliesBlockResources
    {
        public const string EmojiButtonFlyoutEmojiSectionNavigationViewItemContent = "CommentRepliesBlock.EmojiButtonFlyoutEmojiSectionNavigationViewItem.Content";
        public const string EmojiButtonFlyoutStickersSectionNavigationViewItemContent = "CommentRepliesBlock.EmojiButtonFlyoutStickersSectionNavigationViewItem.Content";
        public const string RepliesAreEmptyTextBlockText = "CommentRepliesBlock.RepliesAreEmptyTextBlock.Text";
    }
    public static class CommentsPageResources
    {
        public const string CommentRepliesTeachingTipTitle = "CommentsPage.CommentRepliesTeachingTip.Title";
    }
    public static class DownloadItemResources
    {
        public const string ActionButtonContentOpen = "DownloadItem.ActionButtonContentOpen";
        public const string ActionButtonContentPause = "DownloadItem.ActionButtonContentPause";
        public const string ActionButtonContentRedownload = "DownloadItem.ActionButtonContentRedownload";
        public const string ActionButtonContentResume = "DownloadItem.ActionButtonContentResume";
        public const string ActionButtonContentRetry = "DownloadItem.ActionButtonContentRetry";
        public const string ActionDownloadCancelled = "DownloadItem.ActionDownloadCancelled";
        public const string CancelDownloadItemLabel = "DownloadItem.CancelDownloadItem.Label";
        public const string CheckErrorMessageInDetailItemLabel = "DownloadItem.CheckErrorMessageInDetailItem.Label";
        public const string DownloadCancelled = "DownloadItem.DownloadCancelled";
        public const string DownloadCompleted = "DownloadItem.DownloadCompleted";
        public const string DownloadErrorMessageFormatted = "DownloadItem.DownloadErrorMessageFormatted";
        public const string DownloadPaused = "DownloadItem.DownloadPaused";
        public const string DownloadPending = "DownloadItem.DownloadPending";
        public const string DownloadQueued = "DownloadItem.DownloadQueued";
        public const string DownloadRunningFormatted = "DownloadItem.DownloadRunningFormatted";
        public const string ErrorMessageDialogTitle = "DownloadItem.ErrorMessageDialogTitle";
        public const string GoToPageItemLabel = "DownloadItem.GoToPageItem.Label";
        public const string OpenDownloadLocationItemLabel = "DownloadItem.OpenDownloadLocationItem.Label";
        public const string RedownloadItemLabel = "DownloadItem.RedownloadItem.Label";
    }
    public static class DownloadMacroHelp_TextResources
    {
        public const string Text = "DownloadMacroHelp_Text.Text";
    }
    public static class DownloadPageResources
    {
        public const string CancelAllButtonContent = "DownloadPage.CancelAllButton.Content";
        public const string CancelSelectionButtonDefaultLabel = "DownloadPage.CancelSelectionButtonDefaultLabel";
        public const string CancelSelectionButtonFormatted = "DownloadPage.CancelSelectionButtonFormatted";
        public const string ClearDownloadListButtonContent = "DownloadPage.ClearDownloadListButton.Content";
        public const string DeleteButtonLabel = "DownloadPage.DeleteButton.Label";
        public const string DeleteDownloadHistoryRecordsFormatted = "DownloadPage.DeleteDownloadHistoryRecordsFormatted";
        public const string DownloadListOptionAllQueued = "DownloadPage.DownloadListOptionAllQueued";
        public const string DownloadListOptionCancelled = "DownloadPage.DownloadListOptionCancelled";
        public const string DownloadListOptionCompleted = "DownloadPage.DownloadListOptionCompleted";
        public const string DownloadListOptionCustomSearch = "DownloadPage.DownloadListOptionCustomSearch";
        public const string DownloadListOptionError = "DownloadPage.DownloadListOptionError";
        public const string DownloadListOptionRunning = "DownloadPage.DownloadListOptionRunning";
        public const string FilterAutoSuggestBoxPlaceholderText = "DownloadPage.FilterAutoSuggestBox.PlaceholderText";
        public const string FilterAutoSuggestBoxNoResultFound = "DownloadPage.FilterAutoSuggestBoxNoResultFound";
        public const string ModeFilterComboBoxPlaceholderText = "DownloadPage.ModeFilterComboBox.PlaceholderText";
        public const string PageTitleTextBlockText = "DownloadPage.PageTitleTextBlock.Text";
        public const string PauseAllButtonContent = "DownloadPage.PauseAllButton.Content";
        public const string PauseButtonLabel = "DownloadPage.PauseButton.Label";
        public const string ResumeAllButtonContent = "DownloadPage.ResumeAllButton.Content";
        public const string ResumeButtonLabel = "DownloadPage.ResumeButton.Label";
        public const string SelectAllButtonLabel = "DownloadPage.SelectAllButton.Label";
        public const string StopButtonLabel = "DownloadPage.StopButton.Label";
    }
    public static class DownloadPageDeleteTasksDialogResources
    {
        public const string DeleteLocalFilesContent = "DownloadPageDeleteTasksDialog.DeleteLocalFiles.Content";
        public const string MessageTextBlockText = "DownloadPageDeleteTasksDialog.MessageTextBlock.Text";
    }
    public static class EntryItemResources
    {
        public const string AddToBookmark = "EntryItem.AddToBookmark";
        public const string Copy = "EntryItem.Copy";
        public const string DownloadTaskCreated = "EntryItem.DownloadTaskCreated";
        public const string GenerateLink = "EntryItem.GenerateLink";
        public const string GenerateWebLink = "EntryItem.GenerateWebLink";
        public const string ImageSetToClipBoard = "EntryItem.ImageSetToClipBoard";
        public const string LinkCopiedToClipboard = "EntryItem.LinkCopiedToClipboard";
        public const string MangaSave = "EntryItem.MangaSave";
        public const string MangaSaveAs = "EntryItem.MangaSaveAs";
        public const string OpenInWebBrowser = "EntryItem.OpenInWebBrowser";
        public const string OpenNovel = "EntryItem.OpenNovel";
        public const string OpenUserInfoPage = "EntryItem.OpenUserInfoPage";
        public const string Save = "EntryItem.Save";
        public const string SaveAs = "EntryItem.SaveAs";
        public const string SaveAsCancelled = "EntryItem.SaveAsCancelled";
        public const string Saved = "EntryItem.Saved";
        public const string ShowPixEzQrCode = "EntryItem.ShowPixEzQrCode";
        public const string ShowQRCode = "EntryItem.ShowQRCode";
        public const string TheIllustrationIsAMangaFormatted = "EntryItem.TheIllustrationIsAMangaFormatted";
        public const string TheIllustrationIsAnUgoira = "EntryItem.TheIllustrationIsAnUgoira";
        public const string UserMetricsFollowingsTextBlockText = "EntryItem.UserMetricsFollowingsTextBlock.Text";
        public const string UserMetricsIllustrationCountTextBlockText = "EntryItem.UserMetricsIllustrationCountTextBlock.Text";
        public const string UserMetricsMyPixivUsersTextBlockText = "EntryItem.UserMetricsMyPixivUsersTextBlock.Text";
    }
    public static class EntryViewResources
    {
        public const string AddedToBookmark = "EntryView.AddedToBookmark";
        public const string AddToBookmarkContextItemText = "EntryView.AddToBookmarkContextItem.Text";
        public const string AddToBookmarkTeachingTipCloseButtonContent = "EntryView.AddToBookmarkTeachingTip.CloseButtonContent";
        public const string CopyAppLinkContextItemText = "EntryView.CopyAppLinkContextItem.Text";
        public const string CopyWebLinkContextItemText = "EntryView.CopyWebLinkContextItem.Text";
        public const string IllustrationQrCodeTeachingTipTeachingTipTitle = "EntryView.IllustrationQrCodeTeachingTip.TeachingTipTitle";
        public const string IllustratorQrCodeTeachingTipTeachingTipTitle = "EntryView.IllustratorQrCodeTeachingTip.TeachingTipTitle";
        public const string OpenInBrowserContextItemText = "EntryView.OpenInBrowserContextItem.Text";
        public const string ResultIsEmptyTextBlock = "EntryView.ResultIsEmptyTextBlock";
        public const string SaveContextItemText = "EntryView.SaveContextItem.Text";
        public const string ShowPixEzQrCodeContextItemText = "EntryView.ShowPixEzQrCodeContextItem.Text";
        public const string ShowQrCodeContextItemText = "EntryView.ShowQrCodeContextItem.Text";
    }
    public static class EntryViewerPageResources
    {
        public const string AddedToBookmark = "EntryViewerPage.AddedToBookmark";
        public const string AddToBookmarkTeachingTipCloseButtonContent = "EntryViewerPage.AddToBookmarkTeachingTip.CloseButtonContent";
        public const string Background = "EntryViewerPage.Background";
        public const string BookmarksNavigationViewItemContent = "EntryViewerPage.BookmarksNavigationViewItem.Content";
        public const string CommentsTabContent = "EntryViewerPage.CommentsTab.Content";
        public const string Copy = "EntryViewerPage.Copy";
        public const string FollowingsNavigationViewItemContent = "EntryViewerPage.FollowingsNavigationViewItem.Content";
        public const string FollowingUserItemTitle = "EntryViewerPage.FollowingUserItem.Title";
        public const string IllustrationCountItemTitle = "EntryViewerPage.IllustrationCountItem.Title";
        public const string InfoAndComments = "EntryViewerPage.InfoAndComments";
        public const string InfoTabContent = "EntryViewerPage.InfoTab.Content";
        public const string LoadingNovelTextBlockText = "EntryViewerPage.LoadingNovelTextBlock.Text";
        public const string LockScreen = "EntryViewerPage.LockScreen";
        public const string MangaCountItemTitle = "EntryViewerPage.MangaCountItem.Title";
        public const string Mirror = "EntryViewerPage.Mirror";
        public const string MyPixivUserItemTitle = "EntryViewerPage.MyPixivUserItem.Title";
        public const string MyPixivUserNavigationViewItemContent = "EntryViewerPage.MyPixivUserNavigationViewItem.Content";
        public const string NextIllustration = "EntryViewerPage.NextIllustration";
        public const string NextNovel = "EntryViewerPage.NextNovel";
        public const string NextPageOrIllustration = "EntryViewerPage.NextPageOrIllustration";
        public const string NextPageOrNovel = "EntryViewerPage.NextPageOrNovel";
        public const string NovelCountItemTitle = "EntryViewerPage.NovelCountItem.Title";
        public const string NovelSettings = "EntryViewerPage.NovelSettings";
        public const string NovelSettingsHeaderTextBlockText = "EntryViewerPage.NovelSettingsHeaderTextBlock.Text";
        public const string PrevIllustration = "EntryViewerPage.PrevIllustration";
        public const string PrevNovel = "EntryViewerPage.PrevNovel";
        public const string PrevPageOrIllustration = "EntryViewerPage.PrevPageOrIllustration";
        public const string PrevPageOrNovel = "EntryViewerPage.PrevPageOrNovel";
        public const string QrCodeTeachingTipTitle = "EntryViewerPage.QrCodeTeachingTip.Title";
        public const string RelatedUserNavigationViewItemContent = "EntryViewerPage.RelatedUserNavigationViewItem.Content";
        public const string RelatedWorksTabContent = "EntryViewerPage.RelatedWorksTab.Content";
        public const string RotateClockwise = "EntryViewerPage.RotateClockwise";
        public const string RotateCounterclockwise = "EntryViewerPage.RotateCounterclockwise";
        public const string Save = "EntryViewerPage.Save";
        public const string SaveAs = "EntryViewerPage.SaveAs";
        public const string SetAs = "EntryViewerPage.SetAs";
        public const string SetAsBackgroundSucceededTitle = "EntryViewerPage.SetAsBackgroundSucceededTitle";
        public const string SetAsLockScreenSucceededTitle = "EntryViewerPage.SetAsLockScreenSucceededTitle";
        public const string SetAsSucceededTitle = "EntryViewerPage.SetAsSucceededTitle";
        public const string Share = "EntryViewerPage.Share";
        public const string ShareTitleFormatted = "EntryViewerPage.ShareTitleFormatted";
        public const string WorkNavigationViewItemContent = "EntryViewerPage.WorkNavigationViewItem.Content";
        public const string ZoomIn = "EntryViewerPage.ZoomIn";
        public const string ZoomOut = "EntryViewerPage.ZoomOut";
    }
    public static class ExitDialogResources
    {
        public const string ClearConfigText = "ExitDialog.ClearConfig.Text";
        public const string ClearContextText = "ExitDialog.ClearContext.Text";
        public const string ContentDialogCloseButtonText = "ExitDialog.ContentDialog.CloseButtonText";
        public const string ContentDialogPrimaryButtonText = "ExitDialog.ContentDialog.PrimaryButtonText";
        public const string ContentDialogTitle = "ExitDialog.ContentDialog.Title";
        public const string MainTextBlockText = "ExitDialog.MainTextBlock.Text";
        public const string OpenLocalFolderText = "ExitDialog.OpenLocalFolder.Text";
        public const string OpenLogFolderText = "ExitDialog.OpenLogFolder.Text";
        public const string ReconfirmationOfClosingWindowTitle = "ExitDialog.ReconfirmationOfClosingWindow.Title";
        public const string ReconfirmationOfClosingWindowCheckBoxContent = "ExitDialog.ReconfirmationOfClosingWindowCheckBox.Content";
        public const string SignOutConfirmationDialogContent = "ExitDialog.SignOutConfirmationDialogContent";
        public const string SignOutConfirmationDialogTitle = "ExitDialog.SignOutConfirmationDialogTitle";
    }
    public static class ExtensionsHelp_TextResources
    {
        public const string Text = "ExtensionsHelp_Text.Text";
    }
    public static class ExtensionsPageResources
    {
        public const string AddExtensionsButtonLabel = "ExtensionsPage.AddExtensionsButton.Label";
        public const string DllFileExistedError = "ExtensionsPage.DllFileExistedError";
        public const string DllLoadedSuccessfully = "ExtensionsPage.DllLoadedSuccessfully";
        public const string DllLoadFailed = "ExtensionsPage.DllLoadFailed";
        public const string ExtensionOutdated = "ExtensionsPage.ExtensionOutdated";
        public const string ExtensionsHelpButtonLabel = "ExtensionsPage.ExtensionsHelpButton.Label";
        public const string OpenExtensionsButtonLabel = "ExtensionsPage.OpenExtensionsButton.Label";
        public const string SomeExtensionsOutdatedFormatted = "ExtensionsPage.SomeExtensionsOutdatedFormatted";
        public const string TitleTextBlockText = "ExtensionsPage.TitleTextBlock.Text";
        public const string UnloadExtensionsButtonLabel = "ExtensionsPage.UnloadExtensionsButton.Label";
        public const string UnzipFailed = "ExtensionsPage.UnzipFailed";
        public const string ZipContainsNoDll = "ExtensionsPage.ZipContainsNoDll";
    }
    public static class FeedPageResources
    {
        public const string CondensedBookmarkFormatted = "FeedPage.CondensedBookmarkFormatted";
        public const string CondensedFollowUserFormatted = "FeedPage.CondensedFollowUserFormatted";
        public const string CondensedPostIllustFormatted = "FeedPage.CondensedPostIllustFormatted";
        public const string FeedListTextBlockText = "FeedPage.FeedListTextBlock.Text";
        public const string SparseBookmarkFormatted = "FeedPage.SparseBookmarkFormatted";
        public const string SparseFollowUserFormatted = "FeedPage.SparseFollowUserFormatted";
        public const string SparsePostIllustFormatted = "FeedPage.SparsePostIllustFormatted";
    }
    public static class FollowingUserBadgeResources
    {
        public const string FollowingTextBlockText = "FollowingUserBadge.FollowingTextBlock.Text";
    }
    public static class HelpPageResources
    {
        public const string AppLinkHelpText = "HelpPage.AppLinkHelp.Text";
        public const string AppLinkHelpExpanderHeader = "HelpPage.AppLinkHelpExpander.Header";
        public const string DownloadMacroHelpExpanderHeader = "HelpPage.DownloadMacroHelpExpander.Header";
        public const string ExtensionsHelpExpanderHeader = "HelpPage.ExtensionsHelpExpander.Header";
        public const string QueryFilterHelpExpanderHeader = "HelpPage.QueryFilterHelpExpander.Header";
        public const string QueryFilterHelpHeaderText = "HelpPage.QueryFilterHelpHeader.Text";
        public const string QueryFilterSimpleHelpHeaderText = "HelpPage.QueryFilterSimpleHelpHeader.Text";
        public const string TitleTextBlockText = "HelpPage.TitleTextBlock.Text";
    }
    public static class IllustrationResultFilterContentResources
    {
        public const string ExcludeTagsEntryHeader = "IllustrationResultFilterContent.ExcludeTagsEntry.Header";
        public const string ExcludeTagTokenInputPlaceholderText = "IllustrationResultFilterContent.ExcludeTagTokenInput.PlaceholderText";
        public const string IllustrationIdEntryHeader = "IllustrationResultFilterContent.IllustrationIdEntry.Header";
        public const string IllustrationIdInputPlaceholderText = "IllustrationResultFilterContent.IllustrationIdInput.PlaceholderText";
        public const string IllustrationNameEntryHeader = "IllustrationResultFilterContent.IllustrationNameEntry.Header";
        public const string IllustrationNameInputPlaceholderText = "IllustrationResultFilterContent.IllustrationNameInput.PlaceholderText";
        public const string IllustratorIdEntryHeader = "IllustrationResultFilterContent.IllustratorIdEntry.Header";
        public const string IllustratorIdInputPlaceholderText = "IllustrationResultFilterContent.IllustratorIdInput.PlaceholderText";
        public const string IllustratorNameEntryHeader = "IllustrationResultFilterContent.IllustratorNameEntry.Header";
        public const string IllustratorNameInputPlaceholderText = "IllustrationResultFilterContent.IllustratorNameInput.PlaceholderText";
        public const string IncludeTagsEntryHeader = "IllustrationResultFilterContent.IncludeTagsEntry.Header";
        public const string IncludeTagTokenInputPlaceholderText = "IllustrationResultFilterContent.IncludeTagTokenInput.PlaceholderText";
        public const string LeastBookmarkCountEntryHeader = "IllustrationResultFilterContent.LeastBookmarkCountEntry.Header";
        public const string LeastBookmarkCountNumberBoxPlaceholderText = "IllustrationResultFilterContent.LeastBookmarkCountNumberBox.PlaceholderText";
        public const string MaximumBookmarkCountEntryHeader = "IllustrationResultFilterContent.MaximumBookmarkCountEntry.Header";
        public const string MaximumBookmarkCountNumberBoxPlaceholderText = "IllustrationResultFilterContent.MaximumBookmarkCountNumberBox.PlaceholderText";
        public const string PublishDateEndEntryHeader = "IllustrationResultFilterContent.PublishDateEndEntry.Header";
        public const string PublishDateEndPickerPlaceholderText = "IllustrationResultFilterContent.PublishDateEndPicker.PlaceholderText";
        public const string PublishDateStartEntryHeader = "IllustrationResultFilterContent.PublishDateStartEntry.Header";
        public const string PublishDateStartPickerPlaceholderText = "IllustrationResultFilterContent.PublishDateStartPicker.PlaceholderText";
        public const string UserGroupNameEntryHeader = "IllustrationResultFilterContent.UserGroupNameEntry.Header";
        public const string UserGroupNameInputPlaceholderText = "IllustrationResultFilterContent.UserGroupNameInput.PlaceholderText";
    }
    public static class IllustratorViewerPageResources
    {
        public const string Follow = "IllustratorViewerPage.Follow";
        public const string OpenInWebBrowser = "IllustratorViewerPage.OpenInWebBrowser";
        public const string PrivateFollow = "IllustratorViewerPage.PrivateFollow";
        public const string Unfollow = "IllustratorViewerPage.Unfollow";
    }
    public static class ImageViewerPageResources
    {
        public const string ApplyingTransformerExtensions = "ImageViewerPage.ApplyingTransformerExtensions";
        public const string CheckingCache = "ImageViewerPage.CheckingCache";
        public const string DownloadingImageFormatted = "ImageViewerPage.DownloadingImageFormatted";
        public const string LoadingFromCache = "ImageViewerPage.LoadingFromCache";
        public const string LoadingImage = "ImageViewerPage.LoadingImage";
        public const string MergingUgoiraFrames = "ImageViewerPage.MergingUgoiraFrames";
        public const string TransformerExtensionFailed = "ImageViewerPage.TransformerExtensionFailed";
        public const string TransformerExtensionFinishedSuccessfully = "ImageViewerPage.TransformerExtensionFinishedSuccessfully";
    }
    public static class IPListInputResources
    {
        public const string DuplicatesWithExistingIP = "IPListInput.DuplicatesWithExistingIP";
        public const string InvalidIPFormat = "IPListInput.InvalidIPFormat";
    }
    public static class LoginPageResources
    {
        public const string BrowserButtonContent = "LoginPage.BrowserButton.Content";
        public const string BrowserHelpToolTipServiceToolTip = "LoginPage.BrowserHelp.ToolTipService.ToolTip";
        public const string BrowserLoginTipMessage = "LoginPage.BrowserLoginTip.Message";
        public const string BrowserLoginTipTitle = "LoginPage.BrowserLoginTip.Title";
        public const string DisableDomainFrontingToggleSwitchHeader = "LoginPage.DisableDomainFrontingToggleSwitch.Header";
        public const string DisableDomainFrontingToggleSwitchOffContent = "LoginPage.DisableDomainFrontingToggleSwitch.OffContent";
        public const string DisableDomainFrontingToggleSwitchOnContent = "LoginPage.DisableDomainFrontingToggleSwitch.OnContent";
        public const string ErrorWhileLoggingInTitle = "LoginPage.ErrorWhileLoggingInTitle";
        public const string ErrorWhileLogginInContentFormatted = "LoginPage.ErrorWhileLogginInContentFormatted";
        public const string FetchingSessionFailedContent = "LoginPage.FetchingSessionFailedContent";
        public const string FetchingSessionFailedTitle = "LoginPage.FetchingSessionFailedTitle";
        public const string LoginPhaseCheckingWebView2Installation = "LoginPage.LoginPhaseCheckingWebView2Installation";
        public const string LoginPhaseRefreshing = "LoginPage.LoginPhaseRefreshing";
        public const string LoginPhaseSuccessNavigating = "LoginPage.LoginPhaseSuccessNavigating";
        public const string LoginPhaseWaitingForUserInput = "LoginPage.LoginPhaseWaitingForUserInput";
        public const string PasswordBoxPlaceholderText = "LoginPage.PasswordBox.PlaceholderText";
        public const string RefreshTokenBoxPlaceholderText = "LoginPage.RefreshTokenBox.PlaceholderText";
        public const string RefreshTokenButtonContent = "LoginPage.RefreshTokenButton.Content";
        public const string SubmitButtonContent = "LoginPage.SubmitButton.Content";
        public const string SubmitWithNewAccountButtonText = "LoginPage.SubmitWithNewAccountButton.Text";
        public const string UserNameBoxPlaceholderText = "LoginPage.UserNameBox.PlaceholderText";
        public const string WebView2InstallationRequiredContent = "LoginPage.WebView2InstallationRequiredContent";
        public const string WebView2InstallationRequiredTitle = "LoginPage.WebView2InstallationRequiredTitle";
        public const string WebViewButtonContent = "LoginPage.WebViewButton.Content";
        public const string WebViewHelpToolTipServiceToolTip = "LoginPage.WebViewHelp.ToolTipService.ToolTip";
        public const string WebViewLoginTipMessage = "LoginPage.WebViewLoginTip.Message";
        public const string WebViewLoginTipTitle = "LoginPage.WebViewLoginTip.Title";
    }
    public static class MacroParserResources
    {
        public const string ExpectedAndOrAfterLeftParFormatted = "MacroParser.ExpectedAndOrAfterLeftParFormatted";
        public const string ExpectedAtLeastTwoNumericInDateFormatted = "MacroParser.ExpectedAtLeastTwoNumericInDateFormatted";
        public const string ExpectedRightBracketOrParenInRangeFormatted = "MacroParser.ExpectedRightBracketOrParenInRangeFormatted";
        public const string ExpectedTokenAfterAtMarkFormatted = "MacroParser.ExpectedTokenAfterAtMarkFormatted";
        public const string FilterQueryError = "MacroParser.FilterQueryError";
        public const string FilterTokenFinishedFormatted = "MacroParser.FilterTokenFinishedFormatted";
        public const string IndexRangeUsedMoreThanOnce = "MacroParser.IndexRangeUsedMoreThanOnce";
        public const string InvalidConstraintFormatted = "MacroParser.InvalidConstraintFormatted";
        public const string MacroShouldBeContainedFormatted = "MacroParser.MacroShouldBeContainedFormatted";
        public const string MacroShouldBeInLastSegmentFormatted = "MacroParser.MacroShouldBeInLastSegmentFormatted";
        public const string MinimumShouldBeSmallerThanMaximiumFormatted = "MacroParser.MinimumShouldBeSmallerThanMaximiumFormatted";
        public const string NegationNotAllowedFormatted = "MacroParser.NegationNotAllowedFormatted";
        public const string NonParameterizedMacroBearingParameterFormatted = "MacroParser.NonParameterizedMacroBearingParameterFormatted";
        public const string NumericTooLargeFormatted = "MacroParser.NumericTooLargeFormatted";
        public const string NumericTooSmallInRangeFormatted = "MacroParser.NumericTooSmallInRangeFormatted";
        public const string ParameterizedMacroMissingParameterFormatted = "MacroParser.ParameterizedMacroMissingParameterFormatted";
        public const string ParserOutOfRange = "MacroParser.ParserOutOfRange";
        public const string ResultIsEmpty = "MacroParser.ResultIsEmpty";
        public const string UnbalancedParFormatted = "MacroParser.UnbalancedParFormatted";
        public const string UnexpactedTokenFormatted = "MacroParser.UnexpactedTokenFormatted";
        public const string UnexpectedTokenFormatted = "MacroParser.UnexpectedTokenFormatted";
        public const string UnknownArtist = "MacroParser.UnknownArtist";
        public const string UnknownIllustrationTitle = "MacroParser.UnknownIllustrationTitle";
        public const string UnknownMacroNameFormatted = "MacroParser.UnknownMacroNameFormatted";
    }
    public static class MainPageResources
    {
        public const string AboutTabContent = "MainPage.AboutTab.Content";
        public const string AiShowItemText = "MainPage.AiShowItem.Text";
        public const string BookmarksTabContent = "MainPage.BookmarksTab.Content";
        public const string DownloadListTabContent = "MainPage.DownloadListTab.Content";
        public const string ExtensionsTabContent = "MainPage.ExtensionsTab.Content";
        public const string FeedTabContent = "MainPage.FeedTab.Content";
        public const string FeedTabCannotBeOpenedContent = "MainPage.FeedTabCannotBeOpenedContent";
        public const string FeedTabCannotBeOpenedTitle = "MainPage.FeedTabCannotBeOpenedTitle";
        public const string FollowingsTabContent = "MainPage.FollowingsTab.Content";
        public const string HelpTabContent = "MainPage.HelpTab.Content";
        public const string HistoriesTabContent = "MainPage.HistoriesTab.Content";
        public const string IllustrationHeaderSuggestionTextBlockText = "MainPage.IllustrationHeaderSuggestionTextBlock.Text";
        public const string LoginTabContent = "MainPage.LoginTab.Content";
        public const string LogoutItemText = "MainPage.LogoutItem.Text";
        public const string MainPageAutoSuggestionBoxPlaceholderText = "MainPage.MainPageAutoSuggestionBox.PlaceholderText";
        public const string MoreViewingSettingsItemText = "MainPage.MoreViewingSettingsItem.Text";
        public const string NewWorksTabContent = "MainPage.NewWorksTab.Content";
        public const string NovelHeaderSuggestionTextBlockText = "MainPage.NovelHeaderSuggestionTextBlock.Text";
        public const string OpenMyPageInBrowserItemText = "MainPage.OpenMyPageInBrowserItem.Text";
        public const string OpenMyPageItemText = "MainPage.OpenMyPageItem.Text";
        public const string OpenSearchSettingButtonToolTipServiceToolTip = "MainPage.OpenSearchSettingButton.ToolTipService.ToolTip";
        public const string RankingsTabContent = "MainPage.RankingsTab.Content";
        public const string RecentPostsTabContent = "MainPage.RecentPostsTab.Content";
        public const string RecommendationsTabContent = "MainPage.RecommendationsTab.Content";
        public const string RecommendUsersTabContent = "MainPage.RecommendUsersTab.Content";
        public const string RefreshingSessionFailedContent = "MainPage.RefreshingSessionFailedContent";
        public const string RefreshingSessionFailedTitle = "MainPage.RefreshingSessionFailedTitle";
        public const string RestrictedModeItemText = "MainPage.RestrictedModeItem.Text";
        public const string ReverseSearchApiKeyNotPresentTitle = "MainPage.ReverseSearchApiKeyNotPresentTitle";
        public const string ReverseSearchButtonToolTipServiceToolTip = "MainPage.ReverseSearchButton.ToolTipService.ToolTip";
        public const string ReverseSearchClientSideErrorContent = "MainPage.ReverseSearchClientSideErrorContent";
        public const string ReverseSearchDropHintTextBlockText = "MainPage.ReverseSearchDropHintTextBlock.Text";
        public const string ReverseSearchErrorTitle = "MainPage.ReverseSearchErrorTitle";
        public const string ReverseSearchNotFoundContent = "MainPage.ReverseSearchNotFoundContent";
        public const string ReverseSearchNotFoundTitle = "MainPage.ReverseSearchNotFoundTitle";
        public const string ReverseSearchResponseContentIsEmpty = "MainPage.ReverseSearchResponseContentIsEmpty";
        public const string ReverseSearchServerSideErrorContent = "MainPage.ReverseSearchServerSideErrorContent";
        public const string ReverseSearchStartContent = "MainPage.ReverseSearchStartContent";
        public const string SearchKeywordCannotBeBlankContent = "MainPage.SearchKeywordCannotBeBlankContent";
        public const string SearchKeywordCannotBeBlankTitle = "MainPage.SearchKeywordCannotBeBlankTitle";
        public const string SearchUsersResult = "MainPage.SearchUsersResult";
        public const string SearchWorksResult = "MainPage.SearchWorksResult";
        public const string SettingsEntryHeaderSuggestionTextBlockText = "MainPage.SettingsEntryHeaderSuggestionTextBlock.Text";
        public const string SettingsTabContent = "MainPage.SettingsTab.Content";
        public const string SpotlightsTabContent = "MainPage.SpotlightsTab.Content";
        public const string TagAutoCompletionSuggestionTextBlockText = "MainPage.TagAutoCompletionSuggestionTextBlock.Text";
        public const string TagsTabContent = "MainPage.TagsTab.Content";
    }
    public static class MessageContentDialogResources
    {
        public const string CancelButtonContent = "MessageContentDialog.CancelButtonContent";
        public const string OkButtonContent = "MessageContentDialog.OkButtonContent";
    }
    public static class MiscResources
    {
        public const string AcrylicBackdrop = "Misc.AcrylicBackdrop";
        public const string AddBookmark = "Misc.AddBookmark";
        public const string AllCountedTagName = "Misc.AllCountedTagName";
        public const string AppThemeDark = "Misc.AppThemeDark";
        public const string AppThemeLight = "Misc.AppThemeLight";
        public const string AppThemeSystemDefault = "Misc.AppThemeSystemDefault";
        public const string BackToWindow = "Misc.BackToWindow";
        public const string Black = "Misc.Black";
        public const string Bmp = "Misc.Bmp";
        public const string Bold = "Misc.Bold";
        public const string BookmarkTagSelectorPrivateCheckBoxContent = "Misc.BookmarkTagSelectorPrivateCheckBox.Content";
        public const string CannotFindLoginProxyServerExecutable = "Misc.CannotFindLoginProxyServerExecutable";
        public const string CloseBottomList = "Misc.CloseBottomList";
        public const string DownloadItemMaybeDeleted = "Misc.DownloadItemMaybeDeleted";
        public const string DownloadItemOpenFailed = "Misc.DownloadItemOpenFailed";
        public const string ExceptionEncountered = "Misc.ExceptionEncountered";
        public const string ExtraBlack = "Misc.ExtraBlack";
        public const string ExtraBold = "Misc.ExtraBold";
        public const string ExtraLight = "Misc.ExtraLight";
        public const string Follow = "Misc.Follow";
        public const string FollowPrivately = "Misc.FollowPrivately";
        public const string FullScreen = "Misc.FullScreen";
        public const string Gif = "Misc.Gif";
        public const string GoToPageFormatted = "Misc.GoToPageFormatted";
        public const string Html = "Misc.Html";
        public const string Jpg = "Misc.Jpg";
        public const string Light = "Misc.Light";
        public const string Md = "Misc.Md";
        public const string Medium = "Misc.Medium";
        public const string MicaAltBackdrop = "Misc.MicaAltBackdrop";
        public const string MicaBackdrop = "Misc.MicaBackdrop";
        public const string NoneBackdrop = "Misc.NoneBackdrop";
        public const string Normal = "Misc.Normal";
        public const string OpenBottomList = "Misc.OpenBottomList";
        public const string OpenIllustId = "Misc.OpenIllustId";
        public const string OpenNovelId = "Misc.OpenNovelId";
        public const string OpenUserId = "Misc.OpenUserId";
        public const string OriginalIllustration = "Misc.OriginalIllustration";
        public const string OriginalTxt = "Misc.OriginalTxt";
        public const string OriginalUgoira = "Misc.OriginalUgoira";
        public const string Pause = "Misc.Pause";
        public const string Pdf = "Misc.Pdf";
        public const string Play = "Misc.Play";
        public const string Png = "Misc.Png";
        public const string PrivacyPolicyComboBoxPlaceholderText = "Misc.PrivacyPolicyComboBox.PlaceholderText";
        public const string PrivacyPolicyPrivate = "Misc.PrivacyPolicyPrivate";
        public const string PrivacyPolicyPublic = "Misc.PrivacyPolicyPublic";
        public const string ProxyOptionNone = "Misc.ProxyOptionNone";
        public const string ProxyOptionSystem = "Misc.ProxyOptionSystem";
        public const string RemoveBookmark = "Misc.RemoveBookmark";
        public const string ReplyContentTooLong = "Misc.ReplyContentTooLong";
        public const string RestoreOriginalResolution = "Misc.RestoreOriginalResolution";
        public const string SearchIllustrationTagMatchOptionExactMatchForTags = "Misc.SearchIllustrationTagMatchOptionExactMatchForTags";
        public const string SearchIllustrationTagMatchOptionPartialMatchForTags = "Misc.SearchIllustrationTagMatchOptionPartialMatchForTags";
        public const string SearchIllustrationTagMatchOptionTitleAndCaption = "Misc.SearchIllustrationTagMatchOptionTitleAndCaption";
        public const string SearchNovelTagMatchOptionCaption = "Misc.SearchNovelTagMatchOptionCaption";
        public const string SearchNovelTagMatchOptionExactMatchForTags = "Misc.SearchNovelTagMatchOptionExactMatchForTags";
        public const string SearchNovelTagMatchOptionPartialMatchForTags = "Misc.SearchNovelTagMatchOptionPartialMatchForTags";
        public const string SearchNovelTagMatchOptionText = "Misc.SearchNovelTagMatchOptionText";
        public const string SearchUser = "Misc.SearchUser";
        public const string SemiBold = "Misc.SemiBold";
        public const string SemiLight = "Misc.SemiLight";
        public const string SimpleWorkTypeIllustAndManga = "Misc.SimpleWorkTypeIllustAndManga";
        public const string SimpleWorkTypeNovel = "Misc.SimpleWorkTypeNovel";
        public const string SortOptionComboBoxPlaceholderText = "Misc.SortOptionComboBox.PlaceholderText";
        public const string TargetFilterForAndroid = "Misc.TargetFilterForAndroid";
        public const string TargetFilterForIOS = "Misc.TargetFilterForIOS";
        public const string Thin = "Misc.Thin";
        public const string ThumbnailDirectionLandscape = "Misc.ThumbnailDirectionLandscape";
        public const string ThumbnailDirectionPortrait = "Misc.ThumbnailDirectionPortrait";
        public const string Tiff = "Misc.Tiff";
        public const string UnexpectedBehavior = "Misc.UnexpectedBehavior";
        public const string Unfollow = "Misc.Unfollow";
        public const string UniformToFillResolution = "Misc.UniformToFillResolution";
        public const string WebPLossless = "Misc.WebPLossless";
        public const string WebPLossy = "Misc.WebPLossy";
        public const string WorkSortOptionDoNotSort = "Misc.WorkSortOptionDoNotSort";
        public const string WorkSortOptionPopularityDescending = "Misc.WorkSortOptionPopularityDescending";
        public const string WorkSortOptionPublishDateAscending = "Misc.WorkSortOptionPublishDateAscending";
        public const string WorkSortOptionPublishDateDescending = "Misc.WorkSortOptionPublishDateDescending";
        public const string WorkTypeComboBoxPlaceholderText = "Misc.WorkTypeComboBox.PlaceholderText";
        public const string WorkTypeIllust = "Misc.WorkTypeIllust";
        public const string WorkTypeManga = "Misc.WorkTypeManga";
        public const string WorkTypeNovel = "Misc.WorkTypeNovel";
    }
    public static class NovelViewerPageResources
    {
        public const string ApplyingTransformerExtensions = "NovelViewerPage.ApplyingTransformerExtensions";
        public const string TransformerExtensionFailed = "NovelViewerPage.TransformerExtensionFailed";
        public const string TransformerExtensionFinishedSuccessfully = "NovelViewerPage.TransformerExtensionFinishedSuccessfully";
    }
    public static class PixevalBadgeResources
    {
        public const string Following = "PixevalBadge.Following";
    }
    public static class PixivReplyBarResources
    {
        public const string CommentIsTooShortOrTooLongToastContentFormatted = "PixivReplyBar.CommentIsTooShortOrTooLongToastContentFormatted";
        public const string CommentIsTooShortOrTooLongToastTitle = "PixivReplyBar.CommentIsTooShortOrTooLongToastTitle";
        public const string ReplyContentRichEditBoxPlaceholderText = "PixivReplyBar.ReplyContentRichEditBox.PlaceholderText";
        public const string SendButtonToolTipServiceToolTip = "PixivReplyBar.SendButton.ToolTipService.ToolTip";
    }
    public static class QueryFilterHelp_TextResources
    {
        public const string Text = "QueryFilterHelp_Text.Text";
    }
    public static class QueryFilterSimpleHelp_TextResources
    {
        public const string Text = "QueryFilterSimpleHelp_Text.Text";
    }
    public static class RankingsPageResources
    {
        public const string RankOptionComboBoxPlaceholderText = "RankingsPage.RankOptionComboBox.PlaceholderText";
        public const string RankOptionDay = "RankingsPage.RankOptionDay";
        public const string RankOptionDayAi = "RankingsPage.RankOptionDayAi";
        public const string RankOptionDayFemale = "RankingsPage.RankOptionDayFemale";
        public const string RankOptionDayFemaleR18 = "RankingsPage.RankOptionDayFemaleR18";
        public const string RankOptionDayMale = "RankingsPage.RankOptionDayMale";
        public const string RankOptionDayMaleR18 = "RankingsPage.RankOptionDayMaleR18";
        public const string RankOptionDayManga = "RankingsPage.RankOptionDayManga";
        public const string RankOptionDayR18 = "RankingsPage.RankOptionDayR18";
        public const string RankOptionDayR18Ai = "RankingsPage.RankOptionDayR18Ai";
        public const string RankOptionMonth = "RankingsPage.RankOptionMonth";
        public const string RankOptionMonthManga = "RankingsPage.RankOptionMonthManga";
        public const string RankOptionWeek = "RankingsPage.RankOptionWeek";
        public const string RankOptionWeekAi = "RankingsPage.RankOptionWeekAi";
        public const string RankOptionWeekAiR18 = "RankingsPage.RankOptionWeekAiR18";
        public const string RankOptionWeekManga = "RankingsPage.RankOptionWeekManga";
        public const string RankOptionWeekOriginal = "RankingsPage.RankOptionWeekOriginal";
        public const string RankOptionWeekR18 = "RankingsPage.RankOptionWeekR18";
        public const string RankOptionWeekR18G = "RankingsPage.RankOptionWeekR18G";
        public const string RankOptionWeekRookie = "RankingsPage.RankOptionWeekRookie";
    }
    public static class ReverseSearchApiKeyNotPresentDialogResources
    {
        public const string MessageTextBlockText = "ReverseSearchApiKeyNotPresentDialog.MessageTextBlock.Text";
        public const string SetApiKeyHyperlinkButtonContent = "ReverseSearchApiKeyNotPresentDialog.SetApiKeyHyperlinkButton.Content";
    }
    public static class SettingsPageResources
    {
        public const string AnimatedPathBlockText = "SettingsPage.AnimatedPathBlock.Text";
        public const string AppDescriptionTextBlockText = "SettingsPage.AppDescriptionTextBlock.Text";
        public const string AppFontFamilyComboBoxPlaceholderText = "SettingsPage.AppFontFamilyComboBox.PlaceholderText";
        public const string AppFontFamilyEntryHeader = "SettingsPage.AppFontFamilyEntry.Header";
        public const string AppLanguageEntryHeader = "SettingsPage.AppLanguageEntry.Header";
        public const string AppLanguageEntryComboBoxPlaceholderText = "SettingsPage.AppLanguageEntryComboBox.PlaceholderText";
        public const string ApplicationSettingsGroupText = "SettingsPage.ApplicationSettingsGroup.Text";
        public const string ArtistIdMacroTooltip = "SettingsPage.ArtistIdMacroTooltip";
        public const string ArtistNameMacroTooltip = "SettingsPage.ArtistNameMacroTooltip";
        public const string BackdropEntryHeader = "SettingsPage.BackdropEntry.Header";
        public const string BackupSettingsEntryDescription = "SettingsPage.BackupSettingsEntry.Description";
        public const string BackupSettingsEntryHeader = "SettingsPage.BackupSettingsEntry.Header";
        public const string BlockedTagsEntryDescription = "SettingsPage.BlockedTagsEntry.Description";
        public const string BlockedTagsEntryHeader = "SettingsPage.BlockedTagsEntry.Header";
        public const string BlockedTagsTokenizingTextBoxPlaceholderText = "SettingsPage.BlockedTagsTokenizingTextBox.PlaceholderText";
        public const string BrowseHistoriesCleared = "SettingsPage.BrowseHistoriesCleared";
        public const string BrowseOriginalImageEntryDescription = "SettingsPage.BrowseOriginalImageEntry.Description";
        public const string BrowseOriginalImageEntryHeader = "SettingsPage.BrowseOriginalImageEntry.Header";
        public const string BrowsingExperienceSettingsGroupText = "SettingsPage.BrowsingExperienceSettingsGroup.Text";
        public const string BugReportChannelsEntryDescription = "SettingsPage.BugReportChannelsEntry.Description";
        public const string BugReportChannelsEntryHeader = "SettingsPage.BugReportChannelsEntry.Header";
        public const string BugReportEntryDescription = "SettingsPage.BugReportEntry.Description";
        public const string BugReportEntryHeader = "SettingsPage.BugReportEntry.Header";
        public const string BuildUpdateAvailable = "SettingsPage.BuildUpdateAvailable";
        public const string CheckForUpdatesButtonContent = "SettingsPage.CheckForUpdatesButton.Content";
        public const string CheckingForUpdate = "SettingsPage.CheckingForUpdate";
        public const string DefaultSearchSortOptionEntryDescription = "SettingsPage.DefaultSearchSortOptionEntry.Description";
        public const string DefaultSearchSortOptionEntryHeader = "SettingsPage.DefaultSearchSortOptionEntry.Header";
        public const string DefaultSearchTagMatchOptionEntryDescription = "SettingsPage.DefaultSearchTagMatchOptionEntry.Description";
        public const string DefaultSearchTagMatchOptionEntryHeader = "SettingsPage.DefaultSearchTagMatchOptionEntry.Header";
        public const string DefaultSelectedTabEntryDescription = "SettingsPage.DefaultSelectedTabEntry.Description";
        public const string DefaultSelectedTabEntryHeader = "SettingsPage.DefaultSelectedTabEntry.Header";
        public const string DeleteBrowseHistoriesButtonContent = "SettingsPage.DeleteBrowseHistoriesButton.Content";
        public const string DeleteBrowseHistoriesEntryDescription = "SettingsPage.DeleteBrowseHistoriesEntry.Description";
        public const string DeleteBrowseHistoriesEntryHeader = "SettingsPage.DeleteBrowseHistoriesEntry.Header";
        public const string DeleteDownloadHistoriesButtonContent = "SettingsPage.DeleteDownloadHistoriesButton.Content";
        public const string DeleteDownloadHistoriesEntryDescription = "SettingsPage.DeleteDownloadHistoriesEntry.Description";
        public const string DeleteDownloadHistoriesEntryHeader = "SettingsPage.DeleteDownloadHistoriesEntry.Header";
        public const string DeleteFileCacheEntryDescription = "SettingsPage.DeleteFileCacheEntry.Description";
        public const string DeleteFileCacheEntryHeader = "SettingsPage.DeleteFileCacheEntry.Header";
        public const string DeleteHistoriesEntryHeader = "SettingsPage.DeleteHistoriesEntry.Header";
        public const string DeleteSearchHistoriesButtonContent = "SettingsPage.DeleteSearchHistoriesButton.Content";
        public const string DeleteSearchHistoriesEntryDescription = "SettingsPage.DeleteSearchHistoriesEntry.Description";
        public const string DeleteSearchHistoriesEntryHeader = "SettingsPage.DeleteSearchHistoriesEntry.Header";
        public const string DonateDeveloperHyperlinkButtonContent = "SettingsPage.DonateDeveloperHyperlinkButton.Content";
        public const string DownloadedAndWaitingToInstall = "SettingsPage.DownloadedAndWaitingToInstall";
        public const string DownloadHistoriesCleared = "SettingsPage.DownloadHistoriesCleared";
        public const string DownloadingUpdate = "SettingsPage.DownloadingUpdate";
        public const string DownloadMacroInvalidInfoBarTitle = "SettingsPage.DownloadMacroInvalidInfoBar.Title";
        public const string DownloadMacroInvalidInfoBarInputCannotBeBlank = "SettingsPage.DownloadMacroInvalidInfoBarInputCannotBeBlank";
        public const string DownloadMacroInvalidInfoBarMacroInvalidFormatted = "SettingsPage.DownloadMacroInvalidInfoBarMacroInvalidFormatted";
        public const string DownloadPathMacroEntryDescription = "SettingsPage.DownloadPathMacroEntry.Description";
        public const string DownloadPathMacroEntryHeader = "SettingsPage.DownloadPathMacroEntry.Header";
        public const string DownloadPathMacroTextBoxPlaceholderText = "SettingsPage.DownloadPathMacroTextBox.PlaceholderText";
        public const string DownloadSettingsGroupText = "SettingsPage.DownloadSettingsGroup.Text";
        public const string DownloadUpdateAutomaticallyEntryDescription = "SettingsPage.DownloadUpdateAutomaticallyEntry.Description";
        public const string DownloadUpdateAutomaticallyEntryHeader = "SettingsPage.DownloadUpdateAutomaticallyEntry.Header";
        public const string DownloadWhenBookmarkedEntryDescription = "SettingsPage.DownloadWhenBookmarkedEntry.Description";
        public const string DownloadWhenBookmarkedEntryHeader = "SettingsPage.DownloadWhenBookmarkedEntry.Header";
        public const string EMailBugReportEntryToolTipServiceToolTip = "SettingsPage.EMailBugReportEntry.ToolTipService.ToolTip";
        public const string EnableDomainFrontingEntryDescription = "SettingsPage.EnableDomainFrontingEntry.Description";
        public const string EnableDomainFrontingEntryHeader = "SettingsPage.EnableDomainFrontingEntry.Header";
        public const string ExportSettingsPlaintextEntryDescription = "SettingsPage.ExportSettingsPlaintextEntry.Description";
        public const string ExportSettingsPlaintextEntryHeader = "SettingsPage.ExportSettingsPlaintextEntry.Header";
        public const string ExportSettingsSuccess = "SettingsPage.ExportSettingsSuccess";
        public const string ExtMacroTooltip = "SettingsPage.ExtMacroTooltip";
        public const string FeedbackByEmailHyperlinkButtonContent = "SettingsPage.FeedbackByEmailHyperlinkButton.Content";
        public const string FileCacheCleared = "SettingsPage.FileCacheCleared";
        public const string GitHubBugReportEntryToolTipServiceToolTip = "SettingsPage.GitHubBugReportEntry.ToolTipService.ToolTip";
        public const string GitHubCheckForUpdatesEntryHeader = "SettingsPage.GitHubCheckForUpdatesEntry.Header";
        public const string GitHubRepositoryHyperlinkButtonContent = "SettingsPage.GitHubRepositoryHyperlinkButton.Content";
        public const string IdMacroTooltip = "SettingsPage.IdMacroTooltip";
        public const string IfAiMacroTooltip = "SettingsPage.IfAiMacroTooltip";
        public const string IfNovelMacroTooltip = "SettingsPage.IfNovelMacroTooltip";
        public const string IfPicAllMacroTooltip = "SettingsPage.IfPicAllMacroTooltip";
        public const string IfPicGifMacroTooltip = "SettingsPage.IfPicGifMacroTooltip";
        public const string IfPicOneMacroTooltip = "SettingsPage.IfPicOneMacroTooltip";
        public const string IfPicSetMacroTooltip = "SettingsPage.IfPicSetMacroTooltip";
        public const string IfR18GMacroTooltip = "SettingsPage.IfR18GMacroTooltip";
        public const string IfR18MacroTooltip = "SettingsPage.IfR18MacroTooltip";
        public const string IllustrationOptionEntryHeader = "SettingsPage.IllustrationOptionEntry.Header";
        public const string ImageMirrorServerEntryDescription = "SettingsPage.ImageMirrorServerEntry.Description";
        public const string ImageMirrorServerEntryHeader = "SettingsPage.ImageMirrorServerEntry.Header";
        public const string ImageMirrorServerTextBoxPlaceholderText = "SettingsPage.ImageMirrorServerTextBox.PlaceholderText";
        public const string ImportSessionSuccess = "SettingsPage.ImportSessionSuccess";
        public const string ImportSettingsPlaintextEntryDescription = "SettingsPage.ImportSettingsPlaintextEntry.Description";
        public const string ImportSettingsPlaintextEntryHeader = "SettingsPage.ImportSettingsPlaintextEntry.Header";
        public const string ImportSettingsSuccess = "SettingsPage.ImportSettingsSuccess";
        public const string InstallCanceled = "SettingsPage.InstallCanceled";
        public const string IsInsider = "SettingsPage.IsInsider";
        public const string IsUpToDate = "SettingsPage.IsUpToDate";
        public const string ItemsViewLayoutTypeEntryDescription = "SettingsPage.ItemsViewLayoutTypeEntry.Description";
        public const string ItemsViewLayoutTypeEntryHeader = "SettingsPage.ItemsViewLayoutTypeEntry.Header";
        public const string JoinFeedbackGroupHyperlinkButtonContent = "SettingsPage.JoinFeedbackGroupHyperlinkButton.Content";
        public const string LanguageSystemDefault = "SettingsPage.LanguageSystemDefault";
        public const string LastCheckedPrefix = "SettingsPage.LastCheckedPrefix";
        public const string LossyImageDownloadQualityEntryDescription = "SettingsPage.LossyImageDownloadQualityEntry.Description";
        public const string LossyImageDownloadQualityEntryHeader = "SettingsPage.LossyImageDownloadQualityEntry.Header";
        public const string MacroCopiedToClipboard = "SettingsPage.MacroCopiedToClipboard";
        public const string MajorUpdateAvailable = "SettingsPage.MajorUpdateAvailable";
        public const string MangaOptionEntryHeader = "SettingsPage.MangaOptionEntry.Header";
        public const string MaxDownloadConcurrencyLevelEntryDescription = "SettingsPage.MaxDownloadConcurrencyLevelEntry.Description";
        public const string MaxDownloadConcurrencyLevelEntryHeader = "SettingsPage.MaxDownloadConcurrencyLevelEntry.Header";
        public const string MaximumBrowseHistoryRecordsEntryDescription = "SettingsPage.MaximumBrowseHistoryRecordsEntry.Description";
        public const string MaximumBrowseHistoryRecordsEntryHeader = "SettingsPage.MaximumBrowseHistoryRecordsEntry.Header";
        public const string MaximumBrowseHistoryRecordsNumerBoxPlaceholderText = "SettingsPage.MaximumBrowseHistoryRecordsNumerBox.PlaceholderText";
        public const string MaximumDownloadHistoryRecordsEntryDescription = "SettingsPage.MaximumDownloadHistoryRecordsEntry.Description";
        public const string MaximumDownloadHistoryRecordsEntryHeader = "SettingsPage.MaximumDownloadHistoryRecordsEntry.Header";
        public const string MaximumDownloadHistoryRecordsNumberBoxPlaceholderText = "SettingsPage.MaximumDownloadHistoryRecordsNumberBox.PlaceholderText";
        public const string MaximumSearchHistoryRecordsEntryDescription = "SettingsPage.MaximumSearchHistoryRecordsEntry.Description";
        public const string MaximumSearchHistoryRecordsEntryHeader = "SettingsPage.MaximumSearchHistoryRecordsEntry.Header";
        public const string MaximumSearchHistoryRecordsNumberBoxPlaceholderText = "SettingsPage.MaximumSearchHistoryRecordsNumberBox.PlaceholderText";
        public const string MaximumSuggestionBoxSearchHistoryEntryDescription = "SettingsPage.MaximumSuggestionBoxSearchHistoryEntry.Description";
        public const string MaximumSuggestionBoxSearchHistoryEntryHeader = "SettingsPage.MaximumSuggestionBoxSearchHistoryEntry.Header";
        public const string MinorUpdateAvailable = "SettingsPage.MinorUpdateAvailable";
        public const string MiscSettingsGroupText = "SettingsPage.MiscSettingsGroup.Text";
        public const string MsStoreCheckForUpdatesEntryHeader = "SettingsPage.MsStoreCheckForUpdatesEntry.Header";
        public const string NavigationViewOpenPaneWidthEntryDescription = "SettingsPage.NavigationViewOpenPaneWidthEntry.Description";
        public const string NavigationViewOpenPaneWidthEntryHeader = "SettingsPage.NavigationViewOpenPaneWidthEntry.Header";
        public const string NovelFontFamilyComboBoxPlaceholderText = "SettingsPage.NovelFontFamilyComboBox.PlaceholderText";
        public const string NovelFontWeightComboBoxPlaceholderText = "SettingsPage.NovelFontWeightComboBox.PlaceholderText";
        public const string NovelOptionEntryHeader = "SettingsPage.NovelOptionEntry.Header";
        public const string NovelPathBlockText = "SettingsPage.NovelPathBlock.Text";
        public const string NovelSettingsBackgroundEntryDescription = "SettingsPage.NovelSettingsBackgroundEntry.Description";
        public const string NovelSettingsBackgroundEntryHeader = "SettingsPage.NovelSettingsBackgroundEntry.Header";
        public const string NovelSettingsFontColorEntryDescription = "SettingsPage.NovelSettingsFontColorEntry.Description";
        public const string NovelSettingsFontColorEntryHeader = "SettingsPage.NovelSettingsFontColorEntry.Header";
        public const string NovelSettingsFontFamilyEntryHeader = "SettingsPage.NovelSettingsFontFamilyEntry.Header";
        public const string NovelSettingsFontSizeEntryDescription = "SettingsPage.NovelSettingsFontSizeEntry.Description";
        public const string NovelSettingsFontSizeEntryHeader = "SettingsPage.NovelSettingsFontSizeEntry.Header";
        public const string NovelSettingsFontWeightEntryDescription = "SettingsPage.NovelSettingsFontWeightEntry.Description";
        public const string NovelSettingsFontWeightEntryHeader = "SettingsPage.NovelSettingsFontWeightEntry.Header";
        public const string NovelSettingsLineHeightEntryDescription = "SettingsPage.NovelSettingsLineHeightEntry.Description";
        public const string NovelSettingsLineHeightEntryHeader = "SettingsPage.NovelSettingsLineHeightEntry.Header";
        public const string NovelSettingsMaxWidthEntryDescription = "SettingsPage.NovelSettingsMaxWidthEntry.Description";
        public const string NovelSettingsMaxWidthEntryHeader = "SettingsPage.NovelSettingsMaxWidthEntry.Header";
        public const string OpenExtensionsEntryDescription = "SettingsPage.OpenExtensionsEntry.Description";
        public const string OpenExtensionsEntryHeader = "SettingsPage.OpenExtensionsEntry.Header";
        public const string OpenFontSettingsHyperlinkButtonContent = "SettingsPage.OpenFontSettingsHyperlinkButton.Content";
        public const string OpenLanguageSettingsHyperlinkButtonContent = "SettingsPage.OpenLanguageSettingsHyperlinkButton.Content";
        public const string OpenLocalEntryDescription = "SettingsPage.OpenLocalEntry.Description";
        public const string OpenLocalEntryHeader = "SettingsPage.OpenLocalEntry.Header";
        public const string OpenLogEntryDescription = "SettingsPage.OpenLogEntry.Description";
        public const string OpenLogEntryHeader = "SettingsPage.OpenLogEntry.Header";
        public const string OpenSettingsEntryDescription = "SettingsPage.OpenSettingsEntry.Description";
        public const string OpenSettingsEntryHeader = "SettingsPage.OpenSettingsEntry.Header";
        public const string OpenTempEntryDescription = "SettingsPage.OpenTempEntry.Description";
        public const string OpenTempEntryHeader = "SettingsPage.OpenTempEntry.Header";
        public const string OpenWorkInfoByDefaultEntryDescription = "SettingsPage.OpenWorkInfoByDefaultEntry.Description";
        public const string OpenWorkInfoByDefaultEntryHeader = "SettingsPage.OpenWorkInfoByDefaultEntry.Header";
        public const string OverwriteDownloadedFileEntryDescription = "SettingsPage.OverwriteDownloadedFileEntry.Description";
        public const string OverwriteDownloadedFileEntryHeader = "SettingsPage.OverwriteDownloadedFileEntry.Header";
        public const string PerformSignOutButtonContent = "SettingsPage.PerformSignOutButton.Content";
        public const string PicSetIndexMacroTooltip = "SettingsPage.PicSetIndexMacroTooltip";
        public const string PixivNameResolverDescriptionText = "SettingsPage.PixivNameResolverDescription.Text";
        public const string PixivNameResolverHeaderText = "SettingsPage.PixivNameResolverHeader.Text";
        public const string ProxyTextBoxEntryDescription = "SettingsPage.ProxyTextBoxEntry.Description";
        public const string ProxyTextBoxEntryHeader = "SettingsPage.ProxyTextBoxEntry.Header";
        public const string ProxyTextBoxErrorUri = "SettingsPage.ProxyTextBoxErrorUri";
        public const string ProxyTypeEntryDescription = "SettingsPage.ProxyTypeEntry.Description";
        public const string ProxyTypeEntryHeader = "SettingsPage.ProxyTypeEntry.Header";
        public const string PublishDayMacroTooltip = "SettingsPage.PublishDayMacroTooltip";
        public const string PublishMonthMacroTooltip = "SettingsPage.PublishMonthMacroTooltip";
        public const string PublishYearMacroTooltip = "SettingsPage.PublishYearMacroTooltip";
        public const string QQBugReportEntryToolTipServiceToolTip = "SettingsPage.QQBugReportEntry.ToolTipService.ToolTip";
        public const string RankOptionEntryDescription = "SettingsPage.RankOptionEntry.Description";
        public const string RankOptionEntryHeader = "SettingsPage.RankOptionEntry.Header";
        public const string RateEntryDescription = "SettingsPage.RateEntry.Description";
        public const string RateEntryHeader = "SettingsPage.RateEntry.Header";
        public const string ReconfirmationOfClosingWindowEntryDescription = "SettingsPage.ReconfirmationOfClosingWindowEntry.Description";
        public const string ReconfirmationOfClosingWindowEntryHeader = "SettingsPage.ReconfirmationOfClosingWindowEntry.Header";
        public const string ReleaseNotesHyperlinkButtonContent = "SettingsPage.ReleaseNotesHyperlinkButton.Content";
        public const string ReportBugHyperlinkButtonContent = "SettingsPage.ReportBugHyperlinkButton.Content";
        public const string ResetDefaultSettingsButtonContent = "SettingsPage.ResetDefaultSettingsButton.Content";
        public const string ResetDefaultSettingsEntryDescription = "SettingsPage.ResetDefaultSettingsEntry.Description";
        public const string ResetDefaultSettingsEntryHeader = "SettingsPage.ResetDefaultSettingsEntry.Header";
        public const string ResetSettingConfirmationDialogContent = "SettingsPage.ResetSettingConfirmationDialogContent";
        public const string ResetSettingConfirmationDialogTitle = "SettingsPage.ResetSettingConfirmationDialogTitle";
        public const string ReverseSearchApiKeyEntryHeader = "SettingsPage.ReverseSearchApiKeyEntry.Header";
        public const string ReverseSearchApiKeyEntryDescriptionHyperlinkButtonContent = "SettingsPage.ReverseSearchApiKeyEntryDescriptionHyperlinkButton.Content";
        public const string ReverseSearchApiKeyTextBoxPlaceholderText = "SettingsPage.ReverseSearchApiKeyTextBox.PlaceholderText";
        public const string ReverseSearchResultSimilarityThresholdEntryDescription = "SettingsPage.ReverseSearchResultSimilarityThresholdEntry.Description";
        public const string ReverseSearchResultSimilarityThresholdEntryHeader = "SettingsPage.ReverseSearchResultSimilarityThresholdEntry.Header";
        public const string ScrollRateEntryDescription = "SettingsPage.ScrollRateEntry.Description";
        public const string ScrollRateEntryHeader = "SettingsPage.ScrollRateEntry.Header";
        public const string SearchHistoriesCleared = "SettingsPage.SearchHistoriesCleared";
        public const string SearchSettingsGroupText = "SettingsPage.SearchSettingsGroup.Text";
        public const string SessionSettingsGroupText = "SettingsPage.SessionSettingsGroup.Text";
        public const string SetPathBlockText = "SettingsPage.SetPathBlock.Text";
        public const string SignOutEntryDescription = "SettingsPage.SignOutEntry.Description";
        public const string SignOutEntryHeader = "SettingsPage.SignOutEntry.Header";
        public const string SimpleWorkTypeEntryDescription = "SettingsPage.SimpleWorkTypeEntry.Description";
        public const string SimpleWorkTypeEntryHeader = "SettingsPage.SimpleWorkTypeEntry.Header";
        public const string SinglePathBlockText = "SettingsPage.SinglePathBlock.Text";
        public const string SpotlightSearchPageLimitNumberBoxPlaceholderText = "SettingsPage.SpotlightSearchPageLimitNumberBox.PlaceholderText";
        public const string TargetAPIPlatformEntryDescription = "SettingsPage.TargetAPIPlatformEntry.Description";
        public const string TargetAPIPlatformEntryHeader = "SettingsPage.TargetAPIPlatformEntry.Header";
        public const string ThemeEntryHeader = "SettingsPage.ThemeEntry.Header";
        public const string ThemeEntryDescriptionHyperlinkButtonContent = "SettingsPage.ThemeEntryDescriptionHyperlinkButton.Content";
        public const string ThumbnailDirectionEntryDescription = "SettingsPage.ThumbnailDirectionEntry.Description";
        public const string ThumbnailDirectionEntryHeader = "SettingsPage.ThumbnailDirectionEntry.Header";
        public const string TitleMacroTooltip = "SettingsPage.TitleMacroTooltip";
        public const string TitleTextBlockText = "SettingsPage.TitleTextBlock.Text";
        public const string UgoiraOptionEntryHeader = "SettingsPage.UgoiraOptionEntry.Header";
        public const string UnknownUpdateState = "SettingsPage.UnknownUpdateState";
        public const string Unzipping = "SettingsPage.Unzipping";
        public const string UpdateApp = "SettingsPage.UpdateApp";
        public const string UpdateFailed = "SettingsPage.UpdateFailed";
        public const string UpdateFailedInTempFolder = "SettingsPage.UpdateFailedInTempFolder";
        public const string UseFileCacheEntryDescription = "SettingsPage.UseFileCacheEntry.Description";
        public const string UseFileCacheEntryHeader = "SettingsPage.UseFileCacheEntry.Header";
        public const string UseSearchEndDateEntryDescription = "SettingsPage.UseSearchEndDateEntry.Description";
        public const string UseSearchEndDateEntryHeader = "SettingsPage.UseSearchEndDateEntry.Header";
        public const string UseSearchStartDateEntryDescription = "SettingsPage.UseSearchStartDateEntry.Description";
        public const string UseSearchStartDateEntryHeader = "SettingsPage.UseSearchStartDateEntry.Header";
        public const string VersionSettingsGroupText = "SettingsPage.VersionSettingsGroup.Text";
        public const string ViewPixevalWebsiteHyperlinkButtonContent = "SettingsPage.ViewPixevalWebsiteHyperlinkButton.Content";
        public const string WebCookieEntryDescription = "SettingsPage.WebCookieEntry.Description";
        public const string WebCookieEntryHeader = "SettingsPage.WebCookieEntry.Header";
        public const string WebCookieTextBoxPlaceholderText = "SettingsPage.WebCookieTextBox.PlaceholderText";
        public const string WorkDownloadFormatEntryDescription = "SettingsPage.WorkDownloadFormatEntry.Description";
        public const string WorkDownloadFormatEntryHeader = "SettingsPage.WorkDownloadFormatEntry.Header";
    }
    public static class TabPageResources
    {
        public const string RevokeAllTabsButtonToolTipServiceToolTip = "TabPage.RevokeAllTabsButton.ToolTipService.ToolTip";
    }
    public static class TagsEntryResources
    {
        public const string DeleteItemLabel = "TagsEntry.DeleteItem.Label";
        public const string EditTag = "TagsEntry.EditTag";
        public const string EditTagFailed = "TagsEntry.EditTagFailed";
        public const string EditTagItemLabel = "TagsEntry.EditTagItem.Label";
        public const string FetchingWorkInfo = "TagsEntry.FetchingWorkInfo";
        public const string FetchingWorkInfoFailed = "TagsEntry.FetchingWorkInfoFailed";
        public const string GoToPageItemLabel = "TagsEntry.GoToPageItem.Label";
        public const string OpenItemLabel = "TagsEntry.OpenItem.Label";
        public const string OpenLocationItemLabel = "TagsEntry.OpenLocationItem.Label";
        public const string TagsIsUnloaded = "TagsEntry.TagsIsUnloaded";
    }
    public static class TagsPageResources
    {
        public const string TagsFilterTokenizingTextBoxPlaceholderText = "TagsPage.TagsFilterTokenizingTextBox.PlaceholderText";
    }
    public static class TokenInputTextBoxResources
    {
        public const string CaseSensitiveCheckBoxToolTipServiceToolTip = "TokenInputTextBox.CaseSensitiveCheckBox.ToolTipService.ToolTip";
        public const string IsRegularExpressionCheckBoxToolTipServiceToolTip = "TokenInputTextBox.IsRegularExpressionCheckBox.ToolTipService.ToolTip";
        public const string SubmitButtonToolTipServiceToolTip = "TokenInputTextBox.SubmitButton.ToolTipService.ToolTip";
    }
    public static class WorkContainerResources
    {
        public const string AddAllToBookmarkButtonLabel = "WorkContainer.AddAllToBookmarkButton.Label";
        public const string AddAllToBookmarkTitle = "WorkContainer.AddAllToBookmarkTitle";
        public const string AddedAllToBookmarkContentFormatted = "WorkContainer.AddedAllToBookmarkContentFormatted";
        public const string AddToBookmarkTeachingTipCloseButtonContent = "WorkContainer.AddToBookmarkTeachingTip.CloseButtonContent";
        public const string CancelSelectionButtonDefaultLabel = "WorkContainer.CancelSelectionButtonDefaultLabel";
        public const string CancelSelectionButtonFormatted = "WorkContainer.CancelSelectionButtonFormatted";
        public const string DownloadItemsQueuedFormatted = "WorkContainer.DownloadItemsQueuedFormatted";
        public const string FilterAutoSuggestBoxPlaceholderText = "WorkContainer.FilterAutoSuggestBox.PlaceholderText";
        public const string OpenAllInBrowserButtonLabel = "WorkContainer.OpenAllInBrowserButton.Label";
        public const string OpenConditionDialogButtonLabel = "WorkContainer.OpenConditionDialogButton.Label";
        public const string RefreshButtonLabel = "WorkContainer.RefreshButton.Label";
        public const string SaveAllButtonLabel = "WorkContainer.SaveAllButton.Label";
        public const string SelectAllButtonLabel = "WorkContainer.SelectAllButton.Label";
        public const string SelectedTooManyItemsForBookmarkContent = "WorkContainer.SelectedTooManyItemsForBookmarkContent";
        public const string SelectedTooManyItemsForBookmarkTitle = "WorkContainer.SelectedTooManyItemsForBookmarkTitle";
        public const string SelectedTooManyItemsForOpenInBrowserContent = "WorkContainer.SelectedTooManyItemsForOpenInBrowserContent";
        public const string SelectedTooManyItemsForSaveContent = "WorkContainer.SelectedTooManyItemsForSaveContent";
        public const string SelectedTooManyItemsTitle = "WorkContainer.SelectedTooManyItemsTitle";
        public const string SelectionButtonLabel = "WorkContainer.SelectionButton.Label";
    }
    public static class WorkInfoPageResources
    {
        public const string BlockTagMenuItemText = "WorkInfoPage.BlockTagMenuItem.Text";
        public const string CopyOriginalTagMenuItemText = "WorkInfoPage.CopyOriginalTagMenuItem.Text";
        public const string CopyTranslatedTagMenuItemText = "WorkInfoPage.CopyTranslatedTagMenuItem.Text";
        public const string WorkCaptionEmpty = "WorkInfoPage.WorkCaptionEmpty";
        public const string WorkTagListTextBlockText = "WorkInfoPage.WorkTagListTextBlock.Text";
    }
}
