//------------------------------------------------------------------------------  
// <auto-generated>  
//     Running by T4 Text Templates on .NET Framework 4.8.9337.0
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Pixeval
{
    public static class AboutPageResources
    {
        public const string DependenciesSubtitleTextBlockText = "AboutPage.DependenciesSubtitleTextBlock.Text";
        public const string OpenSourceLicenseSubtitleTextBlockText = "AboutPage.OpenSourceLicenseSubtitleTextBlock.Text";
        public const string SpecialThanksSubtitleTextBlockText = "AboutPage.SpecialThanksSubtitleTextBlock.Text";
        public const string TitleTextBlockText = "AboutPage.TitleTextBlock.Text";
    }
    public static class AppSettingsResources
    {
        public const string AppFontFamilyEntryDescription = "AppSettings.AppFontFamilyEntry.Description";
        public const string AppFontFamilyEntryHeader = "AppSettings.AppFontFamilyEntry.Header";
        public const string AppFontFamilyEntryPlaceholder = "AppSettings.AppFontFamilyEntry.Placeholder";
        public const string AppLanguageEntryDescription = "AppSettings.AppLanguageEntry.Description";
        public const string AppLanguageEntryHeader = "AppSettings.AppLanguageEntry.Header";
        public const string AppLanguageEntryPlaceholder = "AppSettings.AppLanguageEntry.Placeholder";
        public const string BlockedTagsEntryDescription = "AppSettings.BlockedTagsEntry.Description";
        public const string BlockedTagsEntryHeader = "AppSettings.BlockedTagsEntry.Header";
        public const string BlockedTagsEntryPlaceholder = "AppSettings.BlockedTagsEntry.Placeholder";
        public const string BrowseDirectionDescription = "AppSettings.BrowseDirection.Description";
        public const string BrowseDirectionHeader = "AppSettings.BrowseDirection.Header";
        public const string BrowseModeDescription = "AppSettings.BrowseMode.Description";
        public const string BrowseModeHeader = "AppSettings.BrowseMode.Header";
        public const string DownloadPathMacroEntryDescription = "AppSettings.DownloadPathMacroEntry.Description";
        public const string DownloadPathMacroEntryHeader = "AppSettings.DownloadPathMacroEntry.Header";
        public const string DownloadUpdateAutomaticallyEntryDescription = "AppSettings.DownloadUpdateAutomaticallyEntry.Description";
        public const string DownloadUpdateAutomaticallyEntryHeader = "AppSettings.DownloadUpdateAutomaticallyEntry.Header";
        public const string EnableGitHubDomainFrontingEntryDescription = "AppSettings.EnableGitHubDomainFrontingEntry.Description";
        public const string EnableGitHubDomainFrontingEntryHeader = "AppSettings.EnableGitHubDomainFrontingEntry.Header";
        public const string EnablePixivDomainFrontingEntryDescription = "AppSettings.EnablePixivDomainFrontingEntry.Description";
        public const string EnablePixivDomainFrontingEntryHeader = "AppSettings.EnablePixivDomainFrontingEntry.Header";
        public const string FileCacheSizeLimitInMegabytesEntryDescription = "AppSettings.FileCacheSizeLimitInMegabytesEntry.Description";
        public const string FileCacheSizeLimitInMegabytesEntryHeader = "AppSettings.FileCacheSizeLimitInMegabytesEntry.Header";
        public const string GitHubNameResolverEntryDescription = "AppSettings.GitHubNameResolverEntry.Description";
        public const string GitHubNameResolverEntryHeader = "AppSettings.GitHubNameResolverEntry.Header";
        public const string HideHomePageCardTitleEntryDescription = "AppSettings.HideHomePageCardTitleEntry.Description";
        public const string HideHomePageCardTitleEntryHeader = "AppSettings.HideHomePageCardTitleEntry.Header";
        public const string HideHomePageToolbarEntryDescription = "AppSettings.HideHomePageToolbarEntry.Description";
        public const string HideHomePageToolbarEntryHeader = "AppSettings.HideHomePageToolbarEntry.Header";
        public const string HomePageColumnsEntryDescription = "AppSettings.HomePageColumnsEntry.Description";
        public const string HomePageColumnsEntryHeader = "AppSettings.HomePageColumnsEntry.Header";
        public const string HomePageRowsEntryDescription = "AppSettings.HomePageRowsEntry.Description";
        public const string HomePageRowsEntryHeader = "AppSettings.HomePageRowsEntry.Header";
        public const string IllustrationViewerAutoPlayIntervalEntryDescription = "AppSettings.IllustrationViewerAutoPlayIntervalEntry.Description";
        public const string IllustrationViewerAutoPlayIntervalEntryHeader = "AppSettings.IllustrationViewerAutoPlayIntervalEntry.Header";
        public const string IllustrationViewerAutoPlayModeEntryDescription = "AppSettings.IllustrationViewerAutoPlayModeEntry.Description";
        public const string IllustrationViewerAutoPlayModeEntryHeader = "AppSettings.IllustrationViewerAutoPlayModeEntry.Header";
        public const string IllustrationViewerAutoPlayScopeEntryDescription = "AppSettings.IllustrationViewerAutoPlayScopeEntry.Description";
        public const string IllustrationViewerAutoPlayScopeEntryHeader = "AppSettings.IllustrationViewerAutoPlayScopeEntry.Header";
        public const string ImageMirrorServerEntryDescription = "AppSettings.ImageMirrorServerEntry.Description";
        public const string ImageMirrorServerEntryHeader = "AppSettings.ImageMirrorServerEntry.Header";
        public const string ImageMirrorServerEntryPlaceholder = "AppSettings.ImageMirrorServerEntry.Placeholder";
        public const string LimitFileCacheSizeEntryDescription = "AppSettings.LimitFileCacheSizeEntry.Description";
        public const string LimitFileCacheSizeEntryHeader = "AppSettings.LimitFileCacheSizeEntry.Header";
        public const string MaxDownloadConcurrencyLevelEntryDescription = "AppSettings.MaxDownloadConcurrencyLevelEntry.Description";
        public const string MaxDownloadConcurrencyLevelEntryHeader = "AppSettings.MaxDownloadConcurrencyLevelEntry.Header";
        public const string NovelSettingsBackgroundEntryDescription = "AppSettings.NovelSettingsBackgroundEntry.Description";
        public const string NovelSettingsBackgroundEntryHeader = "AppSettings.NovelSettingsBackgroundEntry.Header";
        public const string NovelSettingsFontColorEntryDescription = "AppSettings.NovelSettingsFontColorEntry.Description";
        public const string NovelSettingsFontColorEntryHeader = "AppSettings.NovelSettingsFontColorEntry.Header";
        public const string NovelSettingsFontFamilyEntryHeader = "AppSettings.NovelSettingsFontFamilyEntry.Header";
        public const string NovelSettingsFontSizeEntryDescription = "AppSettings.NovelSettingsFontSizeEntry.Description";
        public const string NovelSettingsFontSizeEntryHeader = "AppSettings.NovelSettingsFontSizeEntry.Header";
        public const string NovelSettingsFontWeightEntryDescription = "AppSettings.NovelSettingsFontWeightEntry.Description";
        public const string NovelSettingsFontWeightEntryHeader = "AppSettings.NovelSettingsFontWeightEntry.Header";
        public const string NovelSettingsFontWeightEntryPlaceholder = "AppSettings.NovelSettingsFontWeightEntry.Placeholder";
        public const string NovelSettingsLineHeightEntryDescription = "AppSettings.NovelSettingsLineHeightEntry.Description";
        public const string NovelSettingsLineHeightEntryHeader = "AppSettings.NovelSettingsLineHeightEntry.Header";
        public const string NovelSettingsMaxWidthEntryDescription = "AppSettings.NovelSettingsMaxWidthEntry.Description";
        public const string NovelSettingsMaxWidthEntryHeader = "AppSettings.NovelSettingsMaxWidthEntry.Header";
        public const string OpenUserInfoByDefaultEntryDescription = "AppSettings.OpenUserInfoByDefaultEntry.Description";
        public const string OpenUserInfoByDefaultEntryHeader = "AppSettings.OpenUserInfoByDefaultEntry.Header";
        public const string OpenWorkInfoByDefaultEntryDescription = "AppSettings.OpenWorkInfoByDefaultEntry.Description";
        public const string OpenWorkInfoByDefaultEntryHeader = "AppSettings.OpenWorkInfoByDefaultEntry.Header";
        public const string OverwriteDownloadedFileEntryDescription = "AppSettings.OverwriteDownloadedFileEntry.Description";
        public const string OverwriteDownloadedFileEntryHeader = "AppSettings.OverwriteDownloadedFileEntry.Header";
        public const string PixivDomainFrontingTypeEntryDescription = "AppSettings.PixivDomainFrontingTypeEntry.Description";
        public const string PixivDomainFrontingTypeEntryHeader = "AppSettings.PixivDomainFrontingTypeEntry.Header";
        public const string PixivNameResolverEntryDescription = "AppSettings.PixivNameResolverEntry.Description";
        public const string PixivNameResolverEntryHeader = "AppSettings.PixivNameResolverEntry.Header";
        public const string ProxyTextBoxEntryDescription = "AppSettings.ProxyTextBoxEntry.Description";
        public const string ProxyTextBoxEntryHeader = "AppSettings.ProxyTextBoxEntry.Header";
        public const string ProxyTypeEntryDescription = "AppSettings.ProxyTypeEntry.Description";
        public const string ProxyTypeEntryHeader = "AppSettings.ProxyTypeEntry.Header";
        public const string RankOptionEntryDescription = "AppSettings.RankOptionEntry.Description";
        public const string RankOptionEntryHeader = "AppSettings.RankOptionEntry.Header";
        public const string SauceNaoApiKeyEntryDescription = "AppSettings.SauceNaoApiKeyEntry.Description";
        public const string SauceNaoApiKeyEntryHeader = "AppSettings.SauceNaoApiKeyEntry.Header";
        public const string SauceNaoApiKeyEntryPlaceholder = "AppSettings.SauceNaoApiKeyEntry.Placeholder";
        public const string SettingsGroupApplicationHeader = "AppSettings.SettingsGroup.Application.Header";
        public const string SettingsGroupBrowsingExperienceHeader = "AppSettings.SettingsGroup.BrowsingExperience.Header";
        public const string SettingsGroupDownloadHeader = "AppSettings.SettingsGroup.Download.Header";
        public const string SettingsGroupNetworkHeader = "AppSettings.SettingsGroup.Network.Header";
        public const string SettingsGroupSearchHeader = "AppSettings.SettingsGroup.Search.Header";
        public const string SimpleWorkTypeEntryDescription = "AppSettings.SimpleWorkTypeEntry.Description";
        public const string SimpleWorkTypeEntryHeader = "AppSettings.SimpleWorkTypeEntry.Header";
        public const string TargetAPIPlatformEntryDescription = "AppSettings.TargetAPIPlatformEntry.Description";
        public const string TargetAPIPlatformEntryHeader = "AppSettings.TargetAPIPlatformEntry.Header";
        public const string ThemeEntryDescription = "AppSettings.ThemeEntry.Description";
        public const string ThemeEntryHeader = "AppSettings.ThemeEntry.Header";
        public const string ThumbnailLayoutTypeEntryDescription = "AppSettings.ThumbnailLayoutTypeEntry.Description";
        public const string ThumbnailLayoutTypeEntryHeader = "AppSettings.ThumbnailLayoutTypeEntry.Header";
        public const string UseFileCacheEntryDescription = "AppSettings.UseFileCacheEntry.Description";
        public const string UseFileCacheEntryHeader = "AppSettings.UseFileCacheEntry.Header";
        public const string WebCookieEntryDescription = "AppSettings.WebCookieEntry.Description";
        public const string WebCookieEntryHeader = "AppSettings.WebCookieEntry.Header";
        public const string WebCookieEntryPlaceholder = "AppSettings.WebCookieEntry.Placeholder";
        public const string WorkDownloadFormatEntryDescription = "AppSettings.WorkDownloadFormatEntry.Description";
        public const string WorkDownloadFormatEntryHeader = "AppSettings.WorkDownloadFormatEntry.Header";
        public const string WorkSubscriptionsSettingsEntryDescription = "AppSettings.WorkSubscriptionsSettingsEntry.Description";
        public const string WorkSubscriptionsSettingsEntryHeader = "AppSettings.WorkSubscriptionsSettingsEntry.Header";
    }
    public static class CommentRepliesBlockResources
    {
        public const string EmojiButtonFlyoutEmojiSectionNavigationViewItemContent = "CommentRepliesBlock.EmojiButtonFlyoutEmojiSectionNavigationViewItem.Content";
        public const string EmojiButtonFlyoutStickersSectionNavigationViewItemContent = "CommentRepliesBlock.EmojiButtonFlyoutStickersSectionNavigationViewItem.Content";
    }
    public static class ContentDialogResources
    {
        public const string CancelButtonContent = "ContentDialog.CancelButtonContent";
        public const string OkButtonContent = "ContentDialog.OkButtonContent";
    }
    public static class CultureDefaultSettingsResources
    {
        public const string AppDefaultFontFamilyName = "CultureDefaultSettings.AppDefaultFontFamilyName";
    }
    public static class DownloadItemResources
    {
        public const string ActionButtonContentOpen = "DownloadItem.ActionButtonContentOpen";
        public const string ActionButtonContentPause = "DownloadItem.ActionButtonContentPause";
        public const string ActionButtonContentResume = "DownloadItem.ActionButtonContentResume";
        public const string ActionButtonContentRetry = "DownloadItem.ActionButtonContentRetry";
        public const string ActionDownloadCancelled = "DownloadItem.ActionDownloadCancelled";
        public const string CancelDownloadItemLabel = "DownloadItem.CancelDownloadItem.Label";
        public const string CheckErrorMessageInDetailItemLabel = "DownloadItem.CheckErrorMessageInDetailItem.Label";
        public const string DownloadCancelled = "DownloadItem.DownloadCancelled";
        public const string DownloadCompleted = "DownloadItem.DownloadCompleted";
        public const string DownloadErrorMessageFormatted = "DownloadItem.DownloadErrorMessageFormatted";
        public const string DownloadPaused = "DownloadItem.DownloadPaused";
        public const string DownloadPending = "DownloadItem.DownloadPending";
        public const string DownloadQueued = "DownloadItem.DownloadQueued";
        public const string DownloadRunningFormatted = "DownloadItem.DownloadRunningFormatted";
        public const string ErrorMessageDialogTitle = "DownloadItem.ErrorMessageDialogTitle";
        public const string GoToPageItemLabel = "DownloadItem.GoToPageItem.Label";
        public const string OpenDownloadLocationItemLabel = "DownloadItem.OpenDownloadLocationItem.Label";
        public const string ResetItemLabel = "DownloadItem.ResetItem.Label";
    }
    public static class DownloadPageResources
    {
        public const string CancelSelectionButtonDefaultLabel = "DownloadPage.CancelSelectionButtonDefaultLabel";
        public const string CancelSelectionButtonFormatted = "DownloadPage.CancelSelectionButtonFormatted";
        public const string DeleteButtonLabel = "DownloadPage.DeleteButton.Label";
        public const string DeleteDownloadHistoryRecordsFormatted = "DownloadPage.DeleteDownloadHistoryRecordsFormatted";
        public const string DeleteLocalFilesContent = "DownloadPage.DeleteLocalFiles.Content";
        public const string FilterAutoSuggestBoxPlaceholderText = "DownloadPage.FilterAutoSuggestBox.PlaceholderText";
        public const string FolderSubtitleFormatted = "DownloadPage.FolderSubtitleFormatted";
        public const string PauseButtonLabel = "DownloadPage.PauseButton.Label";
        public const string ResetButtonLabel = "DownloadPage.ResetButton.Label";
        public const string ResumeButtonLabel = "DownloadPage.ResumeButton.Label";
        public const string SelectAllButtonLabel = "DownloadPage.SelectAllButton.Label";
        public const string StopButtonLabel = "DownloadPage.StopButton.Label";
    }
    public static class EntryItemResources
    {
        public const string AddToBookmark = "EntryItem.AddToBookmark";
        public const string AddToWatchLater = "EntryItem.AddToWatchLater";
        public const string Copy = "EntryItem.Copy";
        public const string DownloadTaskCreated = "EntryItem.DownloadTaskCreated";
        public const string GenerateLink = "EntryItem.GenerateLink";
        public const string GenerateWebLink = "EntryItem.GenerateWebLink";
        public const string MangaSave = "EntryItem.MangaSave";
        public const string OpenInWebBrowser = "EntryItem.OpenInWebBrowser";
        public const string OpenUserInfoPage = "EntryItem.OpenUserInfoPage";
        public const string RemoveFromWatchLater = "EntryItem.RemoveFromWatchLater";
        public const string Save = "EntryItem.Save";
        public const string SaveAsCancelled = "EntryItem.SaveAsCancelled";
        public const string TheIllustrationIsAMangaFormatted = "EntryItem.TheIllustrationIsAMangaFormatted";
        public const string TheIllustrationIsAnUgoira = "EntryItem.TheIllustrationIsAnUgoira";
    }
    public static class EntryViewResources
    {
        public const string AddedToBookmark = "EntryView.AddedToBookmark";
        public const string ResultIsEmptyTextBlock = "EntryView.ResultIsEmptyTextBlock";
    }
    public static class EntryViewerPageResources
    {
        public const string AddedToBookmark = "EntryViewerPage.AddedToBookmark";
        public const string AddToBookmarkTeachingTipCloseButtonContent = "EntryViewerPage.AddToBookmarkTeachingTip.CloseButtonContent";
        public const string AutoPlay = "EntryViewerPage.AutoPlay";
        public const string AutoPlayInterval10Seconds = "EntryViewerPage.AutoPlayInterval10Seconds";
        public const string AutoPlayInterval15Seconds = "EntryViewerPage.AutoPlayInterval15Seconds";
        public const string AutoPlayInterval1Second = "EntryViewerPage.AutoPlayInterval1Second";
        public const string AutoPlayInterval30Seconds = "EntryViewerPage.AutoPlayInterval30Seconds";
        public const string AutoPlayInterval3Seconds = "EntryViewerPage.AutoPlayInterval3Seconds";
        public const string AutoPlayInterval5Seconds = "EntryViewerPage.AutoPlayInterval5Seconds";
        public const string CommentsTabContent = "EntryViewerPage.CommentsTab.Content";
        public const string Copy = "EntryViewerPage.Copy";
        public const string FollowingUserItemTitle = "EntryViewerPage.FollowingUserItem.Title";
        public const string IllustrationCountItemTitle = "EntryViewerPage.IllustrationCountItem.Title";
        public const string InfoAndComments = "EntryViewerPage.InfoAndComments";
        public const string InfoTabContent = "EntryViewerPage.InfoTab.Content";
        public const string LoadFailed = "EntryViewerPage.LoadFailed";
        public const string LoadingNovelTextBlockText = "EntryViewerPage.LoadingNovelTextBlock.Text";
        public const string MangaCountItemTitle = "EntryViewerPage.MangaCountItem.Title";
        public const string Mirror = "EntryViewerPage.Mirror";
        public const string MyPixivUserItemTitle = "EntryViewerPage.MyPixivUserItem.Title";
        public const string NextPage = "EntryViewerPage.Next.Page";
        public const string NextPageOrWork = "EntryViewerPage.Next.PageOrWork";
        public const string NextWork = "EntryViewerPage.Next.Work";
        public const string NovelCountItemTitle = "EntryViewerPage.NovelCountItem.Title";
        public const string NovelSettings = "EntryViewerPage.NovelSettings";
        public const string NovelSettingsHeaderTextBlockText = "EntryViewerPage.NovelSettingsHeaderTextBlock.Text";
        public const string OtherImageTransformerExtensions = "EntryViewerPage.OtherImageTransformerExtensions";
        public const string Pin = "EntryViewerPage.Pin";
        public const string PrevPage = "EntryViewerPage.Prev.Page";
        public const string PrevPageOrWork = "EntryViewerPage.Prev.PageOrWork";
        public const string PrevWork = "EntryViewerPage.Prev.Work";
        public const string RelatedWorksTabContent = "EntryViewerPage.RelatedWorksTab.Content";
        public const string RotateClockwise = "EntryViewerPage.RotateClockwise";
        public const string RotateCounterclockwise = "EntryViewerPage.RotateCounterclockwise";
        public const string Save = "EntryViewerPage.Save";
        public const string SetAsSucceededTitle = "EntryViewerPage.SetAsSucceededTitle";
        public const string Share = "EntryViewerPage.Share";
        public const string ShareTitleFormatted = "EntryViewerPage.ShareTitleFormatted";
        public const string ZoomIn = "EntryViewerPage.ZoomIn";
        public const string ZoomOut = "EntryViewerPage.ZoomOut";
        public const string ZoomToFit = "EntryViewerPage.ZoomToFit";
        public const string ZoomToOriginal = "EntryViewerPage.ZoomToOriginal";
    }
    public static class EnumResources
    {
        public const string ApplicationThemeDark = "Enum.ApplicationTheme.Dark";
        public const string ApplicationThemeDefault = "Enum.ApplicationTheme.Default";
        public const string ApplicationThemeLight = "Enum.ApplicationTheme.Light";
        public const string BrowseDirectionBottomUp = "Enum.BrowseDirection.BottomUp";
        public const string BrowseDirectionLeftRight = "Enum.BrowseDirection.LeftRight";
        public const string BrowseDirectionRightLeft = "Enum.BrowseDirection.RightLeft";
        public const string BrowseDirectionTopDown = "Enum.BrowseDirection.TopDown";
        public const string BrowseModeContinuous = "Enum.BrowseMode.Continuous";
        public const string BrowseModeSwipe = "Enum.BrowseMode.Swipe";
        public const string ClearDataKindBrowseHistory = "Enum.ClearDataKind.BrowseHistory";
        public const string ClearDataKindDownloadHistory = "Enum.ClearDataKind.DownloadHistory";
        public const string ClearDataKindFileCache = "Enum.ClearDataKind.FileCache";
        public const string ClearDataKindSearchHistory = "Enum.ClearDataKind.SearchHistory";
        public const string DomainFrontingTypeDesync = "Enum.DomainFrontingType.Desync";
        public const string DomainFrontingTypeFragmentation = "Enum.DomainFrontingType.Fragmentation";
        public const string DownloadListOptionAllQueued = "Enum.DownloadListOption.AllQueued";
        public const string DownloadListOptionCancelled = "Enum.DownloadListOption.Cancelled";
        public const string DownloadListOptionCompleted = "Enum.DownloadListOption.Completed";
        public const string DownloadListOptionCustomSearch = "Enum.DownloadListOption.CustomSearch";
        public const string DownloadListOptionError = "Enum.DownloadListOption.Error";
        public const string DownloadListOptionRunning = "Enum.DownloadListOption.Running";
        public const string FontWeightBlack = "Enum.FontWeight.Black";
        public const string FontWeightBold = "Enum.FontWeight.Bold";
        public const string FontWeightExtraBlack = "Enum.FontWeight.ExtraBlack";
        public const string FontWeightExtraBold = "Enum.FontWeight.ExtraBold";
        public const string FontWeightExtraLight = "Enum.FontWeight.ExtraLight";
        public const string FontWeightLight = "Enum.FontWeight.Light";
        public const string FontWeightMedium = "Enum.FontWeight.Medium";
        public const string FontWeightNormal = "Enum.FontWeight.Normal";
        public const string FontWeightSemiBold = "Enum.FontWeight.SemiBold";
        public const string FontWeightSemiLight = "Enum.FontWeight.SemiLight";
        public const string FontWeightThin = "Enum.FontWeight.Thin";
        public const string HomePageCardSourceKindDescriptionSingleImage = "Enum.HomePageCardSourceKindDescription.SingleImage";
        public const string HomePageCardSourceKindDescriptionSingleNovel = "Enum.HomePageCardSourceKindDescription.SingleNovel";
        public const string HomePageCardSourceKindDescriptionSingleUser = "Enum.HomePageCardSourceKindDescription.SingleUser";
        public const string HomePageCardSourceKindDescriptionSpotlight = "Enum.HomePageCardSourceKindDescription.Spotlight";
        public const string HomePageCardSourceKindDescriptionUserFollowing = "Enum.HomePageCardSourceKindDescription.UserFollowing";
        public const string HomePageCardSourceKindDescriptionUserMyPixiv = "Enum.HomePageCardSourceKindDescription.UserMyPixiv";
        public const string HomePageCardSourceKindDescriptionUserRecommended = "Enum.HomePageCardSourceKindDescription.UserRecommended";
        public const string HomePageCardSourceKindDescriptionUserSearch = "Enum.HomePageCardSourceKindDescription.UserSearch";
        public const string HomePageCardSourceKindDescriptionWorkBookmarks = "Enum.HomePageCardSourceKindDescription.WorkBookmarks";
        public const string HomePageCardSourceKindDescriptionWorkFollowing = "Enum.HomePageCardSourceKindDescription.WorkFollowing";
        public const string HomePageCardSourceKindDescriptionWorkNew = "Enum.HomePageCardSourceKindDescription.WorkNew";
        public const string HomePageCardSourceKindDescriptionWorkPosts = "Enum.HomePageCardSourceKindDescription.WorkPosts";
        public const string HomePageCardSourceKindDescriptionWorkRanking = "Enum.HomePageCardSourceKindDescription.WorkRanking";
        public const string HomePageCardSourceKindDescriptionWorkRecommended = "Enum.HomePageCardSourceKindDescription.WorkRecommended";
        public const string HomePageCardSourceKindDescriptionWorkSearch = "Enum.HomePageCardSourceKindDescription.WorkSearch";
        public const string IllustrationDownloadFormatOriginal = "Enum.IllustrationDownloadFormat.Original";
        public const string IllustrationViewerAutoPlayModeLoop = "Enum.IllustrationViewerAutoPlayMode.Loop";
        public const string IllustrationViewerAutoPlayModeSequential = "Enum.IllustrationViewerAutoPlayMode.Sequential";
        public const string IllustrationViewerAutoPlayScopeAllWorks = "Enum.IllustrationViewerAutoPlayScope.AllWorks";
        public const string IllustrationViewerAutoPlayScopeCurrentWork = "Enum.IllustrationViewerAutoPlayScope.CurrentWork";
        public const string LocalSortOptionDoNotSort = "Enum.LocalSortOption.DoNotSort";
        public const string LocalSortOptionPopularityDescending = "Enum.LocalSortOption.PopularityDescending";
        public const string LocalSortOptionPublishDateAscending = "Enum.LocalSortOption.PublishDateAscending";
        public const string LocalSortOptionPublishDateDescending = "Enum.LocalSortOption.PublishDateDescending";
        public const string NovelDownloadFormatHtml = "Enum.NovelDownloadFormat.Html";
        public const string NovelDownloadFormatMd = "Enum.NovelDownloadFormat.Md";
        public const string NovelDownloadFormatOriginalTxt = "Enum.NovelDownloadFormat.OriginalTxt";
        public const string PrivacyPolicyPrivate = "Enum.PrivacyPolicy.Private";
        public const string PrivacyPolicyPublic = "Enum.PrivacyPolicy.Public";
        public const string ProxyOptionCustom = "Enum.ProxyOption.Custom";
        public const string ProxyOptionNone = "Enum.ProxyOption.None";
        public const string ProxyOptionSystem = "Enum.ProxyOption.System";
        public const string RankOptionDay = "Enum.RankOption.Day";
        public const string RankOptionDayAi = "Enum.RankOption.DayAi";
        public const string RankOptionDayFemale = "Enum.RankOption.DayFemale";
        public const string RankOptionDayFemaleR18 = "Enum.RankOption.DayFemaleR18";
        public const string RankOptionDayMale = "Enum.RankOption.DayMale";
        public const string RankOptionDayMaleR18 = "Enum.RankOption.DayMaleR18";
        public const string RankOptionDayManga = "Enum.RankOption.DayManga";
        public const string RankOptionDayR18 = "Enum.RankOption.DayR18";
        public const string RankOptionDayR18Ai = "Enum.RankOption.DayR18Ai";
        public const string RankOptionMonth = "Enum.RankOption.Month";
        public const string RankOptionMonthManga = "Enum.RankOption.MonthManga";
        public const string RankOptionWeek = "Enum.RankOption.Week";
        public const string RankOptionWeekAi = "Enum.RankOption.WeekAi";
        public const string RankOptionWeekAiR18 = "Enum.RankOption.WeekAiR18";
        public const string RankOptionWeekManga = "Enum.RankOption.WeekManga";
        public const string RankOptionWeekOriginal = "Enum.RankOption.WeekOriginal";
        public const string RankOptionWeekR18 = "Enum.RankOption.WeekR18";
        public const string RankOptionWeekR18G = "Enum.RankOption.WeekR18G";
        public const string RankOptionWeekRookie = "Enum.RankOption.WeekRookie";
        public const string SearchIllustrationContentTypeIllustration = "Enum.SearchIllustrationContentType.Illustration";
        public const string SearchIllustrationContentTypeIllustrationAndMangaAndUgoira = "Enum.SearchIllustrationContentType.IllustrationAndMangaAndUgoira";
        public const string SearchIllustrationContentTypeIllustrationAndUgoira = "Enum.SearchIllustrationContentType.IllustrationAndUgoira";
        public const string SearchIllustrationContentTypeManga = "Enum.SearchIllustrationContentType.Manga";
        public const string SearchIllustrationContentTypeUgoira = "Enum.SearchIllustrationContentType.Ugoira";
        public const string SearchIllustrationRatioPatternAll = "Enum.SearchIllustrationRatioPattern.All";
        public const string SearchIllustrationRatioPatternLandscape = "Enum.SearchIllustrationRatioPattern.Landscape";
        public const string SearchIllustrationRatioPatternPortrait = "Enum.SearchIllustrationRatioPattern.Portrait";
        public const string SearchIllustrationRatioPatternSquare = "Enum.SearchIllustrationRatioPattern.Square";
        public const string SearchIllustrationTagMatchOptionExactMatchForTags = "Enum.SearchIllustrationTagMatchOption.ExactMatchForTags";
        public const string SearchIllustrationTagMatchOptionPartialMatchForTags = "Enum.SearchIllustrationTagMatchOption.PartialMatchForTags";
        public const string SearchIllustrationTagMatchOptionTitleAndCaption = "Enum.SearchIllustrationTagMatchOption.TitleAndCaption";
        public const string SearchNovelContentLengthOptionNone = "Enum.SearchNovelContentLengthOption.None";
        public const string SearchNovelContentLengthOptionReadingTime = "Enum.SearchNovelContentLengthOption.ReadingTime";
        public const string SearchNovelContentLengthOptionTextLength = "Enum.SearchNovelContentLengthOption.TextLength";
        public const string SearchNovelContentLengthOptionWordCount = "Enum.SearchNovelContentLengthOption.WordCount";
        public const string SearchNovelTagMatchOptionExactMatchForTags = "Enum.SearchNovelTagMatchOption.ExactMatchForTags";
        public const string SearchNovelTagMatchOptionKeyword = "Enum.SearchNovelTagMatchOption.Keyword";
        public const string SearchNovelTagMatchOptionPartialMatchForTags = "Enum.SearchNovelTagMatchOption.PartialMatchForTags";
        public const string SearchNovelTagMatchOptionText = "Enum.SearchNovelTagMatchOption.Text";
        public const string SimpleWorkTypeIllustrationAndManga = "Enum.SimpleWorkType.IllustrationAndManga";
        public const string SimpleWorkTypeNovel = "Enum.SimpleWorkType.Novel";
        public const string ThumbnailLayoutTypeGrid = "Enum.ThumbnailLayoutType.Grid";
        public const string ThumbnailLayoutTypeLinedFlow = "Enum.ThumbnailLayoutType.LinedFlow";
        public const string ThumbnailLayoutTypeMasonry = "Enum.ThumbnailLayoutType.Masonry";
        public const string UgoiraDownloadFormatOriginal = "Enum.UgoiraDownloadFormat.Original";
        public const string WorkSortOptionPopularityDescending = "Enum.WorkSortOption.PopularityDescending";
        public const string WorkSortOptionPublishDateAscending = "Enum.WorkSortOption.PublishDateAscending";
        public const string WorkSortOptionPublishDateDescending = "Enum.WorkSortOption.PublishDateDescending";
        public const string WorkSubscriptionTypeBookmarks = "Enum.WorkSubscriptionType.Bookmarks";
        public const string WorkSubscriptionTypePosts = "Enum.WorkSubscriptionType.Posts";
        public const string WorkSubscriptionWorkKindIllustration = "Enum.WorkSubscriptionWorkKind.Illustration";
        public const string WorkSubscriptionWorkKindIllustrationAndManga = "Enum.WorkSubscriptionWorkKind.IllustrationAndManga";
        public const string WorkSubscriptionWorkKindManga = "Enum.WorkSubscriptionWorkKind.Manga";
        public const string WorkSubscriptionWorkKindNovel = "Enum.WorkSubscriptionWorkKind.Novel";
        public const string WorkTypeIllustration = "Enum.WorkType.Illustration";
        public const string WorkTypeManga = "Enum.WorkType.Manga";
        public const string WorkTypeNovel = "Enum.WorkType.Novel";
        public const string WorkTypeEnumIllustration = "Enum.WorkTypeEnum.Illustration";
        public const string WorkTypeEnumManga = "Enum.WorkTypeEnum.Manga";
        public const string WorkTypeEnumNovel = "Enum.WorkTypeEnum.Novel";
        public const string WorkTypeEnumUgoira = "Enum.WorkTypeEnum.Ugoira";
    }
    public static class ExtensionsPageResources
    {
        public const string AddExtensionsButtonLabel = "ExtensionsPage.AddExtensionsButton.Label";
        public const string CancelPendingUninstallExtensionsButtonLabel = "ExtensionsPage.CancelPendingUninstallExtensionsButton.Label";
        public const string ExtensionFileExistedError = "ExtensionsPage.ExtensionFileExistedError";
        public const string ExtensionLoadedSuccessfully = "ExtensionsPage.ExtensionLoadedSuccessfully";
        public const string ExtensionLoadFailed = "ExtensionsPage.ExtensionLoadFailed";
        public const string ExtensionOutdatedFormatted = "ExtensionsPage.ExtensionOutdatedFormatted";
        public const string ExtensionPendingUninstallCancelled = "ExtensionsPage.ExtensionPendingUninstallCancelled";
        public const string ExtensionsHelpButtonLabel = "ExtensionsPage.ExtensionsHelpButton.Label";
        public const string ExtensionsPriorityBottomButtonLabel = "ExtensionsPage.ExtensionsPriorityBottomButton.Label";
        public const string ExtensionsPriorityDownButtonLabel = "ExtensionsPage.ExtensionsPriorityDownButton.Label";
        public const string ExtensionsPriorityTopButtonLabel = "ExtensionsPage.ExtensionsPriorityTopButton.Label";
        public const string ExtensionsPriorityUpButtonLabel = "ExtensionsPage.ExtensionsPriorityUpButton.Label";
        public const string ExtensionWillUninstallOnNextStartup = "ExtensionsPage.ExtensionWillUninstallOnNextStartup";
        public const string MarkedExtensionsPendingUninstallFormatted = "ExtensionsPage.MarkedExtensionsPendingUninstallFormatted";
        public const string MarkedOutdatedExtensionsPendingUninstallFormatted = "ExtensionsPage.MarkedOutdatedExtensionsPendingUninstallFormatted";
        public const string NoExtensionsToUninstall = "ExtensionsPage.NoExtensionsToUninstall";
        public const string NoOutdatedExtensionsToUninstall = "ExtensionsPage.NoOutdatedExtensionsToUninstall";
        public const string OpenExtensionsButtonLabel = "ExtensionsPage.OpenExtensionsButton.Label";
        public const string PlatformNotSupportExtensions = "ExtensionsPage.PlatformNotSupportExtensions";
        public const string SomeExtensionsOutdatedFormatted = "ExtensionsPage.SomeExtensionsOutdatedFormatted";
        public const string SubtitleTextBlockText = "ExtensionsPage.SubtitleTextBlock.Text";
        public const string TitleTextBlockText = "ExtensionsPage.TitleTextBlock.Text";
        public const string UninstallAllExtensionsButtonLabel = "ExtensionsPage.UninstallAllExtensionsButton.Label";
        public const string UninstallExtensionsButtonLabel = "ExtensionsPage.UninstallExtensionsButton.Label";
        public const string UninstallOutdatedExtensionsButtonLabel = "ExtensionsPage.UninstallOutdatedExtensionsButton.Label";
        public const string ZipContainsNoExtension = "ExtensionsPage.ZipContainsNoExtension";
    }
    public static class FeedPageResources
    {
        public const string CondensedBookmarkFormatted = "FeedPage.CondensedBookmarkFormatted";
        public const string CondensedFollowUserFormatted = "FeedPage.CondensedFollowUserFormatted";
        public const string CondensedPostIllustFormatted = "FeedPage.CondensedPostIllustFormatted";
        public const string FeedListTextBlockText = "FeedPage.FeedListTextBlock.Text";
        public const string SparseBookmarkFormatted = "FeedPage.SparseBookmarkFormatted";
        public const string SparseFollowUserFormatted = "FeedPage.SparseFollowUserFormatted";
        public const string SparsePostIllustFormatted = "FeedPage.SparsePostIllustFormatted";
    }
    public static class FilterResources
    {
        public const string CompletionsAnd = "Filter.Completions.And";
        public const string CompletionsAuthor = "Filter.Completions.Author";
        public const string CompletionsBookmark = "Filter.Completions.Bookmark";
        public const string CompletionsEndDate = "Filter.Completions.EndDate";
        public const string CompletionsExcludeAi = "Filter.Completions.Exclude.Ai";
        public const string CompletionsExcludeConstraint = "Filter.Completions.Exclude.Constraint";
        public const string CompletionsExcludeGif = "Filter.Completions.Exclude.Gif";
        public const string CompletionsExcludeR18 = "Filter.Completions.Exclude.R18";
        public const string CompletionsExcludeR18G = "Filter.Completions.Exclude.R18G";
        public const string CompletionsIncludeAi = "Filter.Completions.Include.Ai";
        public const string CompletionsIncludeConstraint = "Filter.Completions.Include.Constraint";
        public const string CompletionsIncludeGif = "Filter.Completions.Include.Gif";
        public const string CompletionsIncludeR18 = "Filter.Completions.Include.R18";
        public const string CompletionsIncludeR18G = "Filter.Completions.Include.R18G";
        public const string CompletionsNot = "Filter.Completions.Not";
        public const string CompletionsOr = "Filter.Completions.Or";
        public const string CompletionsRatio = "Filter.Completions.Ratio";
        public const string CompletionsStartDate = "Filter.Completions.StartDate";
        public const string CompletionsTag = "Filter.Completions.Tag";
        public const string CompletionsTitle = "Filter.Completions.Title";
        public const string CompletionsValueHintsDateFullDash = "Filter.Completions.ValueHints.Date.FullDash";
        public const string CompletionsValueHintsDateFullDot = "Filter.Completions.ValueHints.Date.FullDot";
        public const string CompletionsValueHintsDateMonthDayDash = "Filter.Completions.ValueHints.Date.MonthDayDash";
        public const string CompletionsValueHintsDateMonthDayDot = "Filter.Completions.ValueHints.Date.MonthDayDot";
        public const string CompletionsValueHintsDoubleDecimal = "Filter.Completions.ValueHints.Double.Decimal";
        public const string CompletionsValueHintsDoubleFraction = "Filter.Completions.ValueHints.Double.Fraction";
        public const string CompletionsValueHintsDoubleInteger = "Filter.Completions.ValueHints.Double.Integer";
        public const string CompletionsValueHintsDoubleRangeClosedDecimalFraction = "Filter.Completions.ValueHints.DoubleRange.ClosedDecimalFraction";
        public const string CompletionsValueHintsDoubleRangeClosedFraction = "Filter.Completions.ValueHints.DoubleRange.ClosedFraction";
        public const string CompletionsValueHintsDoubleRangeLower = "Filter.Completions.ValueHints.DoubleRange.Lower";
        public const string CompletionsValueHintsDoubleRangeUpperDecimal = "Filter.Completions.ValueHints.DoubleRange.UpperDecimal";
        public const string CompletionsValueHintsDoubleRangeUpperFraction = "Filter.Completions.ValueHints.DoubleRange.UpperFraction";
        public const string CompletionsValueHintsLongPlain = "Filter.Completions.ValueHints.Long.Plain";
        public const string CompletionsValueHintsLongRangeClosed = "Filter.Completions.ValueHints.LongRange.Closed";
        public const string CompletionsValueHintsLongRangeLower = "Filter.Completions.ValueHints.LongRange.Lower";
        public const string CompletionsValueHintsLongRangeUpper = "Filter.Completions.ValueHints.LongRange.Upper";
        public const string CompletionsValueHintsTextExact = "Filter.Completions.ValueHints.Text.Exact";
        public const string CompletionsValueHintsTextPlain = "Filter.Completions.ValueHints.Text.Plain";
        public const string CompletionsValueHintsTextQuoted = "Filter.Completions.ValueHints.Text.Quoted";
        public const string CompletionsValueHintsTextQuotedExact = "Filter.Completions.ValueHints.Text.QuotedExact";
        public const string DiagnosticsCompletionSuffixFormatted = "Filter.Diagnostics.CompletionSuffixFormatted";
        public const string DiagnosticsDateRequiresMonthAndDay = "Filter.Diagnostics.DateRequiresMonthAndDay";
        public const string DiagnosticsDateValueTooLarge = "Filter.Diagnostics.DateValueTooLarge";
        public const string DiagnosticsDenominatorCannotBeZero = "Filter.Diagnostics.DenominatorCannotBeZero";
        public const string DiagnosticsDoubleRangeOpenIntervalUnsupported = "Filter.Diagnostics.DoubleRangeOpenIntervalUnsupported";
        public const string DiagnosticsExpectedInteger = "Filter.Diagnostics.ExpectedInteger";
        public const string DiagnosticsIntegerOutOfRange = "Filter.Diagnostics.IntegerOutOfRange";
        public const string DiagnosticsInternalExpectedDateValue = "Filter.Diagnostics.InternalExpectedDateValue";
        public const string DiagnosticsInternalExpectedDoubleRangeValue = "Filter.Diagnostics.InternalExpectedDoubleRangeValue";
        public const string DiagnosticsInternalExpectedDoubleValue = "Filter.Diagnostics.InternalExpectedDoubleValue";
        public const string DiagnosticsInternalExpectedLongRangeValue = "Filter.Diagnostics.InternalExpectedLongRangeValue";
        public const string DiagnosticsInternalExpectedLongValue = "Filter.Diagnostics.InternalExpectedLongValue";
        public const string DiagnosticsInternalExpectedTextValue = "Filter.Diagnostics.InternalExpectedTextValue";
        public const string DiagnosticsInvalidDate = "Filter.Diagnostics.InvalidDate";
        public const string DiagnosticsInvalidDoubleRangeFormat = "Filter.Diagnostics.InvalidDoubleRangeFormat";
        public const string DiagnosticsInvalidDoubleValue = "Filter.Diagnostics.InvalidDoubleValue";
        public const string DiagnosticsInvalidLongRangeFormat = "Filter.Diagnostics.InvalidLongRangeFormat";
        public const string DiagnosticsInvalidValue = "Filter.Diagnostics.InvalidValue";
        public const string DiagnosticsMessageWithPositionFormatted = "Filter.Diagnostics.MessageWithPositionFormatted";
        public const string DiagnosticsMissingDateValue = "Filter.Diagnostics.MissingDateValue";
        public const string DiagnosticsMissingDoubleValue = "Filter.Diagnostics.MissingDoubleValue";
        public const string DiagnosticsMissingFractionalPart = "Filter.Diagnostics.MissingFractionalPart";
        public const string DiagnosticsMissingGroupOperator = "Filter.Diagnostics.MissingGroupOperator";
        public const string DiagnosticsMissingLongValue = "Filter.Diagnostics.MissingLongValue";
        public const string DiagnosticsMissingPredicateAfterNegation = "Filter.Diagnostics.MissingPredicateAfterNegation";
        public const string DiagnosticsMissingRangeValue = "Filter.Diagnostics.MissingRangeValue";
        public const string DiagnosticsMissingRightParenthesis = "Filter.Diagnostics.MissingRightParenthesis";
        public const string DiagnosticsMissingStringQuote = "Filter.Diagnostics.MissingStringQuote";
        public const string DiagnosticsMissingTextValue = "Filter.Diagnostics.MissingTextValue";
        public const string DiagnosticsNegativeRangeUnsupported = "Filter.Diagnostics.NegativeRangeUnsupported";
        public const string DiagnosticsRangeMinimumGreaterThanMaximum = "Filter.Diagnostics.RangeMinimumGreaterThanMaximum";
        public const string DiagnosticsUnexpectedToken = "Filter.Diagnostics.UnexpectedToken";
        public const string DiagnosticsUnsupportedValueKind = "Filter.Diagnostics.UnsupportedValueKind";
        public const string FilterQueryError = "Filter.FilterQueryError";
    }
    public static class HelpPageResources
    {
        public const string AppLinkHelpText = "HelpPage.AppLinkHelp.Text";
        public const string AppProtocolLinkHelpExpanderHeader = "HelpPage.AppProtocolLinkHelpExpander.Header";
        public const string DownloadMacroHelpExpanderHeader = "HelpPage.DownloadMacroHelpExpander.Header";
        public const string ExtensionsHelpExpanderHeader = "HelpPage.ExtensionsHelpExpander.Header";
        public const string QueryFilterHelpExpanderHeader = "HelpPage.QueryFilterHelpExpander.Header";
        public const string QueryFilterHelpHeaderText = "HelpPage.QueryFilterHelpHeader.Text";
        public const string QueryFilterSimpleHelpHeaderText = "HelpPage.QueryFilterSimpleHelpHeader.Text";
        public const string TitleTextBlockText = "HelpPage.TitleTextBlock.Text";
    }
    public static class HomePageResources
    {
        public const string AddConfiguredCardButtonContent = "HomePage.AddConfiguredCardButton.Content";
        public const string CardBackgroundTextBlockText = "HomePage.CardBackgroundTextBlock.Text";
        public const string CardLibraryTitleTextBlockText = "HomePage.CardLibraryTitleTextBlock.Text";
        public const string CardPreviewEmptyTextBlockText = "HomePage.CardPreview.EmptyTextBlock.Text";
        public const string CardPreviewFailedTextBlockText = "HomePage.CardPreview.FailedTextBlock.Text";
        public const string CardPreviewLoadingTextBlockText = "HomePage.CardPreview.LoadingTextBlock.Text";
        public const string CardTitleParameterSeparator = "HomePage.CardTitle.ParameterSeparator";
        public const string DeleteSelectedCardButtonContent = "HomePage.DeleteSelectedCardButton.Content";
        public const string EditButtonLabel = "HomePage.EditButton.Label";
        public const string EditPaneDescriptionTextBlockText = "HomePage.EditPaneDescriptionTextBlock.Text";
        public const string EditPaneTitleTextBlockText = "HomePage.EditPaneTitleTextBlock.Text";
        public const string GridColumnsTextBlockText = "HomePage.GridColumnsTextBlock.Text";
        public const string GridRowsTextBlockText = "HomePage.GridRowsTextBlock.Text";
        public const string GridShrinkBlockedWarningContent = "HomePage.GridShrinkBlockedWarning.Content";
        public const string GridShrinkBlockedWarningTitle = "HomePage.GridShrinkBlockedWarning.Title";
        public const string GridSizeTitleTextBlockText = "HomePage.GridSizeTitleTextBlock.Text";
        public const string HeightTextBlockText = "HomePage.HeightTextBlock.Text";
        public const string HideCardTitleButtonLabel = "HomePage.HideCardTitleButton.Label";
        public const string HideToolbarButtonLabel = "HomePage.HideToolbarButton.Label";
        public const string InvalidSourceParameterWarningContent = "HomePage.InvalidSourceParameterWarning.Content";
        public const string InvalidSourceParameterWarningTitle = "HomePage.InvalidSourceParameterWarning.Title";
        public const string LayoutConflictWarningContent = "HomePage.LayoutConflictWarning.Content";
        public const string LayoutConflictWarningTitle = "HomePage.LayoutConflictWarning.Title";
        public const string NoSelectedCardTextBlockText = "HomePage.NoSelectedCardTextBlock.Text";
        public const string NoSpaceWarningContent = "HomePage.NoSpaceWarning.Content";
        public const string NoSpaceWarningTitle = "HomePage.NoSpaceWarning.Title";
        public const string OpenCardPageButtonToolTip = "HomePage.OpenCardPageButton.ToolTip";
        public const string PositionXTextBlockText = "HomePage.PositionXTextBlock.Text";
        public const string PositionYTextBlockText = "HomePage.PositionYTextBlock.Text";
        public const string SelectCardSourcePromptTextBlockText = "HomePage.SelectCardSourcePromptTextBlock.Text";
        public const string SelectedCardTitleTextBlockText = "HomePage.SelectedCardTitleTextBlock.Text";
        public const string SourceEntryIdTextBlockText = "HomePage.Source.EntryIdTextBlock.Text";
        public const string SourcePrivacyPolicyTextBlockText = "HomePage.Source.PrivacyPolicyTextBlock.Text";
        public const string SourceRankingDateTextBlockText = "HomePage.Source.RankingDateTextBlock.Text";
        public const string SourceRankOptionTextBlockText = "HomePage.Source.RankOptionTextBlock.Text";
        public const string SourceSearchTextTextBlockText = "HomePage.Source.SearchTextTextBlock.Text";
        public const string SourceSimpleWorkTypeTextBlockText = "HomePage.Source.SimpleWorkTypeTextBlock.Text";
        public const string SourceTagTextBlockText = "HomePage.Source.TagTextBlock.Text";
        public const string SourceUserIdTextBlockText = "HomePage.Source.UserIdTextBlock.Text";
        public const string SourceUseSpecifiedRankingDateCheckBoxContent = "HomePage.Source.UseSpecifiedRankingDateCheckBox.Content";
        public const string SourceWorkTypeTextBlockText = "HomePage.Source.WorkTypeTextBlock.Text";
        public const string SourceParametersTitleTextBlockText = "HomePage.SourceParametersTitleTextBlock.Text";
        public const string WidthTextBlockText = "HomePage.WidthTextBlock.Text";
    }
    public static class ImageViewerPageResources
    {
        public const string ApplyingTransformerExtensions = "ImageViewerPage.ApplyingTransformerExtensions";
        public const string CheckingCache = "ImageViewerPage.CheckingCache";
        public const string DownloadingImageFormatted = "ImageViewerPage.DownloadingImageFormatted";
        public const string LoadingFromCache = "ImageViewerPage.LoadingFromCache";
        public const string LoadingImage = "ImageViewerPage.LoadingImage";
        public const string MergingUgoiraFrames = "ImageViewerPage.MergingUgoiraFrames";
        public const string TransformerExtensionFailed = "ImageViewerPage.TransformerExtensionFailed";
        public const string TransformerExtensionFinishedSuccessfully = "ImageViewerPage.TransformerExtensionFinishedSuccessfully";
    }
    public static class IPListInputResources
    {
        public const string DuplicatesWithExistingIP = "IPListInput.DuplicatesWithExistingIP";
        public const string InvalidIPFormat = "IPListInput.InvalidIPFormat";
    }
    public static class LoginPageResources
    {
        public const string FetchingSessionFailedContent = "LoginPage.FetchingSessionFailed.Content";
        public const string FetchingSessionFailedTitle = "LoginPage.FetchingSessionFailed.Title";
        public const string LoginHeader = "LoginPage.LoginHeader";
        public const string RefreshTokenBoxPlaceholderText = "LoginPage.RefreshTokenBox.PlaceholderText";
        public const string RefreshTokenButtonContent = "LoginPage.RefreshTokenButton.Content";
        public const string WebViewButtonContent = "LoginPage.WebViewButton.Content";
    }
    public static class MacroParserResources
    {
        public const string ConditionalBranchesMissing = "MacroParser.ConditionalBranchesMissing";
        public const string ExpectedLeftBraceAfterAt = "MacroParser.ExpectedLeftBraceAfterAt";
        public const string ExpectedMacroName = "MacroParser.ExpectedMacroName";
        public const string InvalidFormatter = "MacroParser.InvalidFormatter";
        public const string MacroDescriptionArtistId = "MacroParser.MacroDescription.ArtistId";
        public const string MacroDescriptionArtistName = "MacroParser.MacroDescription.ArtistName";
        public const string MacroDescriptionExt = "MacroParser.MacroDescription.Ext";
        public const string MacroDescriptionId = "MacroParser.MacroDescription.Id";
        public const string MacroDescriptionIsAi = "MacroParser.MacroDescription.IsAi";
        public const string MacroDescriptionIsBookmarkGroup = "MacroParser.MacroDescription.IsBookmarkGroup";
        public const string MacroDescriptionIsGroup = "MacroParser.MacroDescription.IsGroup";
        public const string MacroDescriptionIsNovel = "MacroParser.MacroDescription.IsNovel";
        public const string MacroDescriptionIsPicGif = "MacroParser.MacroDescription.IsPicGif";
        public const string MacroDescriptionIsPicOne = "MacroParser.MacroDescription.IsPicOne";
        public const string MacroDescriptionIsPicSet = "MacroParser.MacroDescription.IsPicSet";
        public const string MacroDescriptionIsPostGroup = "MacroParser.MacroDescription.IsPostGroup";
        public const string MacroDescriptionIsR18 = "MacroParser.MacroDescription.IsR18";
        public const string MacroDescriptionIsR18G = "MacroParser.MacroDescription.IsR18G";
        public const string MacroDescriptionPicSetIndex = "MacroParser.MacroDescription.PicSetIndex";
        public const string MacroDescriptionPublishTime = "MacroParser.MacroDescription.PublishTime";
        public const string MacroDescriptionTitle = "MacroParser.MacroDescription.Title";
        public const string MacroShouldBeContained = "MacroParser.MacroShouldBeContained";
        public const string MacroShouldBeInLastSegment = "MacroParser.MacroShouldBeInLastSegment";
        public const string MessageWithPositionFormatted = "MacroParser.MessageWithPositionFormatted";
        public const string MissingConditionalSeparator = "MacroParser.MissingConditionalSeparator";
        public const string MissingRightBrace = "MacroParser.MissingRightBrace";
        public const string NonParameterizedMacroBearingParameter = "MacroParser.NonParameterizedMacroBearingParameter";
        public const string UnexpectedToken = "MacroParser.UnexpectedToken";
        public const string UnknownMacroName = "MacroParser.UnknownMacroName";
    }
    public static class MainPageResources
    {
        public const string AiShowItemText = "MainPage.AiShowItem.Text";
        public const string LoggingInDescription = "MainPage.LoggingIn.Description";
        public const string LoggingInFailed = "MainPage.LoggingIn.Failed";
        public const string LoggingInHeader = "MainPage.LoggingIn.Header";
        public const string MoreViewingSettingsItemText = "MainPage.MoreViewingSettingsItem.Text";
        public const string OpenMyPageInBrowserItemText = "MainPage.OpenMyPageInBrowserItem.Text";
        public const string OpenMyPageItemText = "MainPage.OpenMyPageItem.Text";
        public const string RestrictedModeItemText = "MainPage.RestrictedModeItem.Text";
        public const string SearchKeywordCannotBeBlankContent = "MainPage.SearchKeywordCannotBeBlank.Content";
        public const string SearchKeywordCannotBeBlankTitle = "MainPage.SearchKeywordCannotBeBlank.Title";
        public const string SearchResultFormatted = "MainPage.SearchResultFormatted";
        public const string SwitchAccountItemText = "MainPage.SwitchAccountItem.Text";
        public const string TabAbout = "MainPage.Tab.About";
        public const string TabBrowsingHistory = "MainPage.Tab.BrowsingHistory";
        public const string TabDownload = "MainPage.Tab.Download";
        public const string TabExtensions = "MainPage.Tab.Extensions";
        public const string TabFeed = "MainPage.Tab.Feed";
        public const string TabHelp = "MainPage.Tab.Help";
        public const string TabHome = "MainPage.Tab.Home";
        public const string TabLogin = "MainPage.Tab.Login";
        public const string TabRelatedUser = "MainPage.Tab.RelatedUser";
        public const string TabSauceNaoResult = "MainPage.Tab.SauceNaoResult";
        public const string TabSearch = "MainPage.Tab.Search";
        public const string TabSettings = "MainPage.Tab.Settings";
        public const string TabSingleImage = "MainPage.Tab.SingleImage";
        public const string TabSingleNovel = "MainPage.Tab.SingleNovel";
        public const string TabSingleUser = "MainPage.Tab.SingleUser";
        public const string TabSpotlight = "MainPage.Tab.Spotlight";
        public const string TabUserFollowing = "MainPage.Tab.UserFollowing";
        public const string TabUserMyPixiv = "MainPage.Tab.UserMyPixiv";
        public const string TabUserRecommended = "MainPage.Tab.UserRecommended";
        public const string TabUserSearch = "MainPage.Tab.UserSearch";
        public const string TabWatchLater = "MainPage.Tab.WatchLater";
        public const string TabWorkBookmarks = "MainPage.Tab.WorkBookmarks";
        public const string TabWorkFollowing = "MainPage.Tab.WorkFollowing";
        public const string TabWorkNew = "MainPage.Tab.WorkNew";
        public const string TabWorkPosts = "MainPage.Tab.WorkPosts";
        public const string TabWorkRanking = "MainPage.Tab.WorkRanking";
        public const string TabWorkRecommended = "MainPage.Tab.WorkRecommended";
        public const string TabWorkSearch = "MainPage.Tab.WorkSearch";
    }
    public static class MiscResources
    {
        public const string AddedToWatchLater = "Misc.AddedToWatchLater";
        public const string AllCountedTagName = "Misc.AllCountedTagName";
        public const string CloseBottomList = "Misc.CloseBottomList";
        public const string Copied = "Misc.Copied";
        public const string DownloadItemMaybeDeleted = "Misc.DownloadItemMaybeDeleted";
        public const string DownloadItemOpenFailed = "Misc.DownloadItemOpenFailed";
        public const string ExceptionEncountered = "Misc.ExceptionEncountered";
        public const string GoToPageFormatted = "Misc.GoToPageFormatted";
        public const string OpenBottomList = "Misc.OpenBottomList";
        public const string Pause = "Misc.Pause";
        public const string PixevalBadgeFollowing = "Misc.PixevalBadge.Following";
        public const string Play = "Misc.Play";
        public const string RemovedFromWatchLater = "Misc.RemovedFromWatchLater";
        public const string UnexpectedBehavior = "Misc.UnexpectedBehavior";
    }
    public static class NovelViewerPageResources
    {
        public const string ApplyingTransformerExtensions = "NovelViewerPage.ApplyingTransformerExtensions";
        public const string TransformerExtensionFailed = "NovelViewerPage.TransformerExtensionFailed";
        public const string TransformerExtensionFinishedSuccessfully = "NovelViewerPage.TransformerExtensionFinishedSuccessfully";
    }
    public static class PixivReplyBarResources
    {
        public const string CommentIsTooShortOrTooLongToastContentFormatted = "PixivReplyBar.CommentIsTooShortOrTooLongToastContentFormatted";
        public const string CommentIsTooShortOrTooLongToastTitle = "PixivReplyBar.CommentIsTooShortOrTooLongToastTitle";
        public const string ReplyContentRichEditBoxPlaceholderText = "PixivReplyBar.ReplyContentRichEditBox.PlaceholderText";
        public const string SendButtonToolTip = "PixivReplyBar.SendButton.ToolTip";
    }
    public static class ReverseSearchApiKeyNotPresentDialogResources
    {
        public const string MessageTextBlockText = "ReverseSearchApiKeyNotPresentDialog.MessageTextBlock.Text";
        public const string SetApiKeyHyperlinkButtonContent = "ReverseSearchApiKeyNotPresentDialog.SetApiKeyHyperlinkButton.Content";
    }
    public static class SearchResources
    {
        public const string AdvancedOptionsIllustrationTab = "Search.AdvancedOptions.IllustrationTab";
        public const string AdvancedOptionsNovelTab = "Search.AdvancedOptions.NovelTab";
        public const string AdvancedOptionsSauceNaoTab = "Search.AdvancedOptions.SauceNaoTab";
        public const string CommonEndDate = "Search.Common.EndDate";
        public const string CommonIncludePotentialViolationWorks = "Search.Common.IncludePotentialViolationWorks";
        public const string CommonIncludeTranslatedTagResults = "Search.Common.IncludeTranslatedTagResults";
        public const string CommonMergePlainKeywordResults = "Search.Common.MergePlainKeywordResults";
        public const string CommonShowAiWorks = "Search.Common.ShowAiWorks";
        public const string CommonSortOption = "Search.Common.SortOption";
        public const string CommonStartDate = "Search.Common.StartDate";
        public const string CommonUnspecified = "Search.Common.Unspecified";
        public const string IllustrationContentType = "Search.Illustration.ContentType";
        public const string IllustrationHeightMax = "Search.Illustration.HeightMax";
        public const string IllustrationHeightMin = "Search.Illustration.HeightMin";
        public const string IllustrationMatchOption = "Search.Illustration.MatchOption";
        public const string IllustrationRatioPattern = "Search.Illustration.RatioPattern";
        public const string IllustrationTool = "Search.Illustration.Tool";
        public const string IllustrationWidthMax = "Search.Illustration.WidthMax";
        public const string IllustrationWidthMin = "Search.Illustration.WidthMin";
        public const string NovelContentLengthMax = "Search.Novel.ContentLengthMax";
        public const string NovelContentLengthMin = "Search.Novel.ContentLengthMin";
        public const string NovelContentLengthOption = "Search.Novel.ContentLengthOption";
        public const string NovelGenre = "Search.Novel.Genre";
        public const string NovelIsOriginalOnly = "Search.Novel.IsOriginalOnly";
        public const string NovelIsReplaceableOnly = "Search.Novel.IsReplaceableOnly";
        public const string NovelLanguage = "Search.Novel.Language";
        public const string NovelMatchOption = "Search.Novel.MatchOption";
        public const string OpenIdIllustration = "Search.OpenId.Illustration";
        public const string OpenIdNovel = "Search.OpenId.Novel";
        public const string OpenIdUser = "Search.OpenId.User";
        public const string SauceNAOOr = "Search.SauceNAO.Or";
        public const string SauceNAOPasteFromClipboard = "Search.SauceNAO.PasteFromClipboard";
        public const string SauceNAOProvideApiKey = "Search.SauceNAO.ProvideApiKey";
        public const string SauceNAOProvideImage = "Search.SauceNAO.ProvideImage";
        public const string SauceNAOSearch = "Search.SauceNAO.Search";
        public const string SearchBoxPlaceholderText = "Search.SearchBox.PlaceholderText";
        public const string SearchHistoryCopy = "Search.SearchHistory.Copy";
        public const string SearchHistoryDelete = "Search.SearchHistory.Delete";
        public const string SearchUser = "Search.SearchUser";
        public const string SectionsCommon = "Search.Sections.Common";
        public const string SectionsIllustration = "Search.Sections.Illustration";
        public const string SectionsNovel = "Search.Sections.Novel";
        public const string TrendingHeaderTextBlockText = "Search.TrendingHeaderTextBlock.Text";
        public const string ValidationInvalidDateRangeContent = "Search.Validation.InvalidDateRange.Content";
        public const string ValidationInvalidDateRangeTitle = "Search.Validation.InvalidDateRange.Title";
        public const string ValidationInvalidNumericRangeContent = "Search.Validation.InvalidNumericRange.Content";
        public const string ValidationInvalidNumericRangeTitle = "Search.Validation.InvalidNumericRange.Title";
        public const string ValidationPremiumSortContent = "Search.Validation.PremiumSort.Content";
        public const string ValidationPremiumSortTitle = "Search.Validation.PremiumSort.Title";
        public const string ValidationSearchFailedTitle = "Search.Validation.SearchFailed.Title";
    }
    public static class SettingsMainViewResources
    {
        public const string AnimatedPathBlockText = "SettingsMainView.AnimatedPathBlock.Text";
        public const string AppDescriptionTextBlockText = "SettingsMainView.AppDescriptionTextBlock.Text";
        public const string BackupSettingsEntryDescription = "SettingsMainView.BackupSettingsEntry.Description";
        public const string BackupSettingsEntryHeader = "SettingsMainView.BackupSettingsEntry.Header";
        public const string BugReportChannelsEntryDescription = "SettingsMainView.BugReportChannelsEntry.Description";
        public const string BugReportChannelsEntryHeader = "SettingsMainView.BugReportChannelsEntry.Header";
        public const string BugReportEntryDescription = "SettingsMainView.BugReportEntry.Description";
        public const string BugReportEntryHeader = "SettingsMainView.BugReportEntry.Header";
        public const string CheckForUpdatesButtonContent = "SettingsMainView.CheckForUpdatesButton.Content";
        public const string CheckingForUpdate = "SettingsMainView.CheckingForUpdate";
        public const string DeleteBrowseHistoriesEntryDescription = "SettingsMainView.DeleteBrowseHistoriesEntry.Description";
        public const string DeleteBrowseHistoriesEntryHeader = "SettingsMainView.DeleteBrowseHistoriesEntry.Header";
        public const string DeleteDownloadHistoriesEntryDescription = "SettingsMainView.DeleteDownloadHistoriesEntry.Description";
        public const string DeleteDownloadHistoriesEntryHeader = "SettingsMainView.DeleteDownloadHistoriesEntry.Header";
        public const string DeleteFileCacheEntryDescription = "SettingsMainView.DeleteFileCacheEntry.Description";
        public const string DeleteFileCacheEntryHeader = "SettingsMainView.DeleteFileCacheEntry.Header";
        public const string DeleteHistoriesEntryHeader = "SettingsMainView.DeleteHistoriesEntry.Header";
        public const string DeleteSearchHistoriesEntryDescription = "SettingsMainView.DeleteSearchHistoriesEntry.Description";
        public const string DeleteSearchHistoriesEntryHeader = "SettingsMainView.DeleteSearchHistoriesEntry.Header";
        public const string DownloadMacroInvalidInfoBarTitle = "SettingsMainView.DownloadMacroInvalidInfoBar.Title";
        public const string DownloadMacroInvalidInfoBarInputCannotBeBlank = "SettingsMainView.DownloadMacroInvalidInfoBarInputCannotBeBlank";
        public const string DownloadMacroInvalidInfoBarMacroInvalidFormatted = "SettingsMainView.DownloadMacroInvalidInfoBarMacroInvalidFormatted";
        public const string DownloadPathMacroTextBoxPlaceholderText = "SettingsMainView.DownloadPathMacroTextBox.PlaceholderText";
        public const string EMailBugReportEntryToolTip = "SettingsMainView.EMailBugReportEntry.ToolTip";
        public const string ExportSettingsPlaintextEntryDescription = "SettingsMainView.ExportSettingsPlaintextEntry.Description";
        public const string ExportSettingsPlaintextEntryHeader = "SettingsMainView.ExportSettingsPlaintextEntry.Header";
        public const string ExportSettingsSuccess = "SettingsMainView.ExportSettingsSuccess";
        public const string FeedbackByEmailHyperlinkButtonContent = "SettingsMainView.FeedbackByEmailHyperlinkButton.Content";
        public const string GitHubBugReportEntryToolTip = "SettingsMainView.GitHubBugReportEntry.ToolTip";
        public const string GitHubCheckForUpdatesEntryHeader = "SettingsMainView.GitHubCheckForUpdatesEntry.Header";
        public const string GitHubRepositoryHyperlinkButtonContent = "SettingsMainView.GitHubRepositoryHyperlinkButton.Content";
        public const string ImportSettingsPlaintextEntryDescription = "SettingsMainView.ImportSettingsPlaintextEntry.Description";
        public const string ImportSettingsPlaintextEntryHeader = "SettingsMainView.ImportSettingsPlaintextEntry.Header";
        public const string ImportSettingsSuccess = "SettingsMainView.ImportSettingsSuccess";
        public const string IsInsider = "SettingsMainView.IsInsider";
        public const string IsUpToDate = "SettingsMainView.IsUpToDate";
        public const string JoinFeedbackGroupHyperlinkButtonContent = "SettingsMainView.JoinFeedbackGroupHyperlinkButton.Content";
        public const string LanguageSystemDefault = "SettingsMainView.LanguageSystemDefault";
        public const string LastCheckedPrefix = "SettingsMainView.LastCheckedPrefix";
        public const string MsStoreCheckForUpdatesEntryHeader = "SettingsMainView.MsStoreCheckForUpdatesEntry.Header";
        public const string NovelPathBlockText = "SettingsMainView.NovelPathBlock.Text";
        public const string OpenExtensionsEntryDescription = "SettingsMainView.OpenExtensionsEntry.Description";
        public const string OpenExtensionsEntryHeader = "SettingsMainView.OpenExtensionsEntry.Header";
        public const string OpenLocalEntryDescription = "SettingsMainView.OpenLocalEntry.Description";
        public const string OpenLocalEntryHeader = "SettingsMainView.OpenLocalEntry.Header";
        public const string OpenLogEntryDescription = "SettingsMainView.OpenLogEntry.Description";
        public const string OpenLogEntryHeader = "SettingsMainView.OpenLogEntry.Header";
        public const string OpenSettingsEntryDescription = "SettingsMainView.OpenSettingsEntry.Description";
        public const string OpenSettingsEntryHeader = "SettingsMainView.OpenSettingsEntry.Header";
        public const string OpenTempEntryDescription = "SettingsMainView.OpenTempEntry.Description";
        public const string OpenTempEntryHeader = "SettingsMainView.OpenTempEntry.Header";
        public const string PredicateMacroHeader = "SettingsMainView.PredicateMacroHeader";
        public const string ProxyTextBoxErrorUri = "SettingsMainView.ProxyTextBoxErrorUri";
        public const string QQBugReportEntryToolTip = "SettingsMainView.QQBugReportEntry.ToolTip";
        public const string RateEntryDescription = "SettingsMainView.RateEntry.Description";
        public const string RateEntryHeader = "SettingsMainView.RateEntry.Header";
        public const string ReleaseNoteDialogEmpty = "SettingsMainView.ReleaseNoteDialog.Empty";
        public const string ReleaseNoteDialogTitleFormatted = "SettingsMainView.ReleaseNoteDialog.TitleFormatted";
        public const string ReleaseNotesHyperlinkButtonContent = "SettingsMainView.ReleaseNotesHyperlinkButton.Content";
        public const string ReportBugHyperlinkButtonContent = "SettingsMainView.ReportBugHyperlinkButton.Content";
        public const string ResetDefaultSettingsEntryDescription = "SettingsMainView.ResetDefaultSettingsEntry.Description";
        public const string ResetDefaultSettingsEntryHeader = "SettingsMainView.ResetDefaultSettingsEntry.Header";
        public const string ResetSettingConfirmationDialogContent = "SettingsMainView.ResetSettingConfirmationDialogContent";
        public const string ResetSettingConfirmationDialogTitle = "SettingsMainView.ResetSettingConfirmationDialogTitle";
        public const string SetPathBlockText = "SettingsMainView.SetPathBlock.Text";
        public const string SettingsSaved = "SettingsMainView.SettingsSaved";
        public const string SinglePathBlockText = "SettingsMainView.SinglePathBlock.Text";
        public const string SwitchAccountEntryDescription = "SettingsMainView.SwitchAccountEntry.Description";
        public const string SwitchAccountEntryHeader = "SettingsMainView.SwitchAccountEntry.Header";
        public const string TitleTextBlockText = "SettingsMainView.TitleTextBlock.Text";
        public const string UpdateAvailableBuild = "SettingsMainView.UpdateAvailable.Build";
        public const string UpdateAvailableMajor = "SettingsMainView.UpdateAvailable.Major";
        public const string UpdateAvailableMinor = "SettingsMainView.UpdateAvailable.Minor";
        public const string UpdateAvailableUnknown = "SettingsMainView.UpdateAvailable.Unknown";
        public const string ViewPixevalWebsiteHyperlinkButtonContent = "SettingsMainView.ViewPixevalWebsiteHyperlinkButton.Content";
    }
    public static class UserViewerPageResources
    {
        public const string Follow = "UserViewerPage.Follow";
        public const string PrivateFollow = "UserViewerPage.PrivateFollow";
        public const string Unfollow = "UserViewerPage.Unfollow";
    }
    public static class WorkContainerResources
    {
        public const string AddedAllToBookmarkContentFormatted = "WorkContainer.AddedAllToBookmarkContentFormatted";
        public const string CancelSelectionButtonDefaultLabel = "WorkContainer.CancelSelectionButtonDefaultLabel";
        public const string CancelSelectionButtonFormatted = "WorkContainer.CancelSelectionButtonFormatted";
        public const string DownloadItemsQueuedFormatted = "WorkContainer.DownloadItemsQueuedFormatted";
        public const string FilterAutoSuggestBoxPlaceholderText = "WorkContainer.FilterAutoSuggestBox.PlaceholderText";
        public const string RefreshButtonLabel = "WorkContainer.RefreshButton.Label";
        public const string SelectAllButtonLabel = "WorkContainer.SelectAllButton.Label";
        public const string SelectedTooManyItemsContent = "WorkContainer.SelectedTooManyItems.Content";
        public const string SelectedTooManyItemsForBookmarkTitle = "WorkContainer.SelectedTooManyItems.ForBookmarkTitle";
        public const string SelectedTooManyItemsForOpenInBrowserContent = "WorkContainer.SelectedTooManyItems.ForOpenInBrowser.Content";
        public const string SelectedTooManyItemsForOpenInBrowserTitle = "WorkContainer.SelectedTooManyItems.ForOpenInBrowser.Title";
        public const string SelectedTooManyItemsForSaveTitle = "WorkContainer.SelectedTooManyItems.ForSaveTitle";
        public const string SelectionButtonLabel = "WorkContainer.SelectionButton.Label";
    }
    public static class WorkInfoPageResources
    {
        public const string BlockTagMenuItemText = "WorkInfoPage.BlockTagMenuItem.Text";
        public const string CopyOriginalTagMenuItemText = "WorkInfoPage.CopyOriginalTagMenuItem.Text";
        public const string CopyTranslatedTagMenuItemText = "WorkInfoPage.CopyTranslatedTagMenuItem.Text";
    }
    public static class WorkSubscriptionsSettingsExpanderResources
    {
        public const string AddSubscriptionButtonLabel = "WorkSubscriptionsSettingsExpander.AddSubscriptionButton.Label";
        public const string InvalidUserId = "WorkSubscriptionsSettingsExpander.InvalidUserId";
        public const string SubscriptionAdded = "WorkSubscriptionsSettingsExpander.SubscriptionAdded";
        public const string UserIdTextBoxPlaceholderText = "WorkSubscriptionsSettingsExpander.UserIdTextBox.PlaceholderText";
    }
    public static class MarkdownResources
    {
        public const string DownloadMacroHelp = "Markdown.DownloadMacroHelp";
        public const string ExtensionsHelp = "Markdown.ExtensionsHelp";
        public const string QueryFilterHelp = "Markdown.QueryFilterHelp";
        public const string QueryFilterSimpleHelp = "Markdown.QueryFilterSimpleHelp";
    }
}
