name: Build-PR

on:
  pull_request:
  
defaults:
  run:
    shell: pwsh

jobs:
    build:
        strategy:
            matrix:
                platform: ['x64','x86','arm64']

        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: actions/setup-dotnet@v2
              with:
                global-json-file: global.json
                include-prerelease: true

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1
              with:
                vs-prerelease: true

            - uses: actions/cache@v3
              with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-nuget-
            - name: Restore the application
              run: msbuild -t:restore -p:Platform=${{ matrix.platform }} -p:RestoreLockedMode=true -m

            - name: Publish the application
              run: msbuild -t:publish -p:Configuration=Debug -p:Platform=${{ matrix.platform }} -p:GenerateAppxPackageOnBuild=true -p:OutDir="$PWD\build" -m

            - name: Copy files
              run: |
                $files = @(Get-ChildItem -Recurse|Where-Object -Property Name -Like Pixeval*.msix)
                Copy-Item $files -Destination ( New-Item -Path ./output -ItemType Directory)
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: Pixeval-${{ matrix.platform }}
                  path: "./output/*"