name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/*.md'
  pull_request:
    branches-ignore:
      - l10n_main

permissions:
  contents: read

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Run unit tests
        run: dotnet test src/Pixeval.Tests/Pixeval.Tests.csproj --configuration Release
